louislam/uptime-kuma

server/model/monitor.js

Quick and easy fix. Could be improved by adding a version number as well. Like `Uptime-Kuma/0.0.1`, for example.

Introduce custom user agent. Fixes #5

---

package-lock.json
package.json
server/notification.js
src/components/NotificationDialog.vue

- Reworked notification code to use Discord webhooks, added a case for tests. Even threw in some fancy colors for the alert embeds.
- Removed discord.js dependency.
- Changed Vue code to just take the webhook URL for the notification dialog
- Made the world a slightly better place.
Fixes #20

Discord notification rework

---

server/notification.js
src/components/NotificationDialog.vue

Adding support for signal notifications through [signal-cli-rest-api](https://github.com/bbernhard/signal-cli-rest-api).

Add support for signal notifications

---

src/assets/app.scss
src/assets/vars.scss
src/components/HeartbeatBar.vue
src/components/Status.vue
src/components/Uptime.vue
src/layouts/Layout.vue
src/pages/Dashboard.vue

basic darkmode

---

src/assets/app.scss
src/assets/vars.scss
src/components/HeartbeatBar.vue
src/components/Status.vue
src/components/Uptime.vue
src/layouts/Layout.vue
src/pages/Dashboard.vue

Reverts louislam/uptime-kuma#32

Revert "basic darkmode"

---

server/notification.js
src/components/NotificationDialog.vue

ref https://github.com/louislam/uptime-kuma/pull/43
closes https://github.com/louislam/uptime-kuma/issues/50

customize Gotify priority

---

server/notification.js
src/components/NotificationDialog.vue

Please test it before merging.

Added Slack webhook notification

---

server/notification.js
src/components/NotificationDialog.vue

Closes #55 
Please test before merging.

Pushover support

---

server/notification.js
src/components/NotificationDialog.vue
src/layouts/Layout.vue

Slack Enhancements and aligns footer to center

---

dockerfile
extra/healthcheck.js

Copied from https://scoutapm.com/blog/how-to-use-docker-healthcheck

Docker Healthcheck

---

public/robots.txt

[Lighthouse] Add robots.txt

---

index.html
src/layouts/Layout.vue

Current report for not logged user (version 1.0.4):
https://github.com/louislam/uptime-kuma/pull/67/commits/db34484ff26d1b6f0fe0a7012dac2ff634320aec fixes:
https://github.com/louislam/uptime-kuma/pull/67/commits/637422494fd2e8afda9e175392c0184f8068de0d fixes:
https://github.com/louislam/uptime-kuma/pull/67/commits/e87b78501bf71ad665c6355b0c88e2e8076dd395 fixes **security and performance** (more info here: https://web.dev/external-anchors-use-rel-noopener/):
https://github.com/louislam/uptime-kuma/pull/67/commits/bfb4a5bcd4f00a7ceb44f4778720dd5914617fd3 fixes:

[Lighthouse] Some improvements

---

src/components/Login.vue

Fixes:
More info: https://web.dev/form-field-multiple-labels/

Fix multiple labels for `Remember me`

---

extra/mark-as-nightly.js

Fix Docker build after https://github.com/louislam/uptime-kuma/pull/69

Fix Docker build

---

server/server.js

Remove debug spam

---

src/pages/Settings.vue

Just small grammar corrections.

Small grammar updates to Settings.vue

---

server/notification.js
src/components/NotificationDialog.vue

Pushover enhancements

---

server/server.js

server will throw exception on database init as passwordHash is not defined.

Fix: passwordHash is not imported

---

.eslintrc.js
package-lock.json
package.json
server/database.js

Having static member in a class is only supported in ES7+ (I think). Bump the version in ESlint will clear the error in `database.js`.

Fix: Update ESLint to handle class static member 

---

server/notification.js
src/components/NotificationDialog.vue

Adds support for LunaSea notifications

---

server/notification.js
src/components/NotificationDialog.vue

adds support for [PUSHY](https://pushy.me) Notifier

FEAT: PUSHY Notifier

---

.eslintrc.js
server/notification.js
src/components/NotificationDialog.vue

Discord enhancements

---

server/database.js

Don't show "Database patch is needed" if database version is newer.

Chore: Improve logging during db development

---

README.md
server/server.js
vite.config.js

Fixes edit action after merging https://github.com/louislam/uptime-kuma/pull/173
Also ESLint `vite.config.json` and fix few markdown lint (https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) warnings

Save `maxredirects` on monitor edit

---

src/assets/app.scss

I really love this project so i wanted to contribute a bit.
This is actually my first pull request i've ever done on Github so hope i did everything alright.
I've noticed that the X from the close button in the NotificationDialog Modal was black.

Fixed Close Button Color in Dark Mode

---

server/notification.js
src/components/NotificationDialog.vue

Add octopush in notification service
(french SMS provider - https://octopush.com/)
Fell free to correct my code if you found something wrong, I'm newbies in JS
Proof of work

Add Octopush Notification Service

---

server/ping-lite.js

I wanted to run this in a FreeBSD jail and had to edit this file for it to use ping.

Add ping support in FreeBSD

---

server/notification.js
src/components/NotificationDialog.vue

Added support for the Line Messenger, you can see the example down below.
**Settings:**
**Example:**

Added Line Messenger Notification Service

---

src/pages/List.vue

As the title says, i also added the new page change animation to the monitor list page.

Added animation for list page change

---

src/util.ts
tsconfig.json

Fix typescript errors by actually defining types, and fix tsconfig file path.

Fix: fix typescript errors

---

server/notification.js
src/components/NotificationDialog.vue

this pull request adds support for mattermost notifications.

added mattermost notification support

---

src/components/PingChart.vue

| light | dark |
| ---- | ---- |
| ![image](https://user-images.githubusercontent.com/3271800/130658424-19ef83a2-6ed5-4bf0-93ff-374570a21c78.png) | ![image](https://user-images.githubusercontent.com/3271800/130658458-ddba3a6a-84fd-414f-8311-6c86910b7f54.png) |
- improve styling of tooltips
- align time axis numbering to grid lines
- finally fix gaps between downtime bars
- add some code comments

Fix: More Chart improvements

---

src/languages/de-DE.js
src/languages/en.js
src/pages/EditMonitor.vue

I added German language support to the new DNS Monitor type.

Added German language for DNS Monitor

---

src/assets/app.scss
src/components/MonitorList.vue
src/layouts/Layout.vue
src/pages/Dashboard.vue
src/pages/DashboardHome.vue
src/pages/Details.vue
src/pages/Settings.vue

I'm using Uptime Kuma with 126 monitors. It's great! But this results in a list that is so long I need to scroll way down to view most of it. Then when I click a monitor to view the details, I'm stuck viewing an empty area until I scroll up again (see screenshot). On mobile, as well, it's usually out of view.
This pull request just implements a function to check if you're scrolled down past the individual monitor detail and scrolls back into view if you click on one in the list.
I'm not a Vue person, so please let me know if there's a cleaner way to do this than using an id attribute. And no worries if you don't want to implement for whatever reason. Thanks!

Scroll to monitor detail if out of view

---

src/main.js

Chinese Translation (from zh-CN.js)

Chinese Translation (from zh-CN.js)

---

src/assets/app.scss

The "Test" btn had dark font color, which is inconsistent with the rest of the UI. This change it to match the rest of the buttons.

Fix: Fix Notification "Test" btn styling

---

README.md

Update `README.md` - Open Collective URL

---

src/languages/ko-KR.js
src/pages/Settings.vue

confirmDisableAuth, new string

Add missing strings for Korean

---

src/languages/da-DK.js
src/languages/de-DE.js
src/languages/en.js
src/languages/es-ES.js
src/languages/fr.js
src/languages/ja.js
src/languages/ko-KR.js
src/languages/nl-NL.js
src/languages/pl.js
src/languages/ru-RU.js
src/languages/sr-latn.js
src/languages/sr.js
src/languages/sv-SE.js
src/languages/zh-CN.js
src/languages/zh-HK.js
src/pages/Setup.vue

As mentioned in this [Card-68125564](https://github.com/louislam/uptime-kuma/projects/1#card-68125564) i added the option to change the language in the setup screen.
I hope it's okay that I just took it off there.

Added set language to the Setup.vue

---

src/languages/de-DE.js
src/languages/en.js
src/pages/Settings.vue

Just added the key  `Clear all statistics` and fixed a minor translation typo in `de-DE`.

Minor translation fixes

---

src/components/NotificationDialog.vue
src/languages/de-DE.js
src/languages/en.js

As mentioned in #386 i changed the wording a little in the notification modal.

Wording correction for notification modal

---

src/pages/Settings.vue

fix(settings): add some button bottom margin for narrow screens

---

src/pages/Settings.vue

Change according to [Card-68608317](https://github.com/louislam/uptime-kuma/projects/1#card-68608317)

Hide 2FA section if disabled auth

---

src/languages/de-DE.js
src/languages/en.js

Added search key

---

package.json
server/notification-providers/teams.js
server/notification.js
src/components/NotificationDialog.vue
src/components/notifications/Teams.vue

- Added Microsoft Teams notification provider

Add microsoft teams notification provider

---

server/server.js

Sorry I didn't have time to test #415. Apparently if the tag doesn't exist, `let tagId = tag.id` would fail since tag is null.
Unfortunately ESlint auto-fix added a few unrelated changes.

Fix: Fix importing tag if tag doesn't exist

---

src/pages/StatusPage.vue

Missed a PR on my branch.
Hides the select monitor input if there is nothing to select.

[status-page] hide select if no monitors to add

---

src/util-frontend.js

Related: https://github.com/louislam/uptime-kuma/pull/391

Remove "Skip Timezone" console log from frontend

---

server/database.js
server/server.js

Closes #433
So uhhh... apparently foreign keys have not been turned on this whole time 😂
Might be why some people are seeing bigger database file than expected.

Fix: clear important beats after deleteMonitor

---

src/assets/app.scss
src/assets/multiselect.scss
src/pages/EditMonitor.vue

Just cleaning up the previous mess.

Chore: Move multiselect css to its own file

---

src/mixins/datetime.js
src/pages/StatusPage.vue

Fixes https://github.com/louislam/uptime-kuma/issues/491
CC: @chakflying 
Related: https://github.com/louislam/uptime-kuma/pull/124

[status-page] Display created and updated time in local timezone. Fixes #491

---

src/components/Login.vue
src/pages/Setup.vue

Improve padding for the Setup and Login input fields

fix(setup): increase left padding input fields + avoid clipping

---

src/assets/app.scss
src/components/HeartbeatBar.vue
src/components/MonitorList.vue
src/components/Uptime.vue

* Improved margins of the healthbar
* Minor eslint fixes for healthbar syntax

fix(heartbeat-bar): cleanup css styling and minor syntax issues

---

.github/ISSUE_TEMPLATE/ask-for-help.yaml
.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml

* Updates the wording of the check-for-duplicates field in the issue forms.

Update the wording used when reporting an Issue via Forms

---

server/notification-providers/feishu.js

Add a status prefix for feishu notification's title.
- Other

Add a status prefix for feishu notification's title

---

src/languages/it-IT.js

Translation update

---

server/notification-providers/dingding.js

Add the status to the title, you can see the message title on the friend list page.
- Other
- Update dingding notification title
> The screenshot is before modification, only the title is modified here

Update dingding notification title

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md
src/languages/README.md

Fix typos. Powered by https://languagetool.org/
- Other

Fix typos in markdown files

---

README.md

Added `Steam Game Server' to the monitor service list.
Fixes #(issue)
NA

Updated monitor service details in README.md

---

server/notification-providers/stackfield.js
server/notification.js
src/components/notifications/Stackfield.vue
src/components/notifications/index.js
src/languages/en.js

Adding support for [Stackfield](https://www.stackfield.com/) notifications.

Add support for Stackfield notifications

---

src/components/notifications/Telegram.vue

Fixes #871
Related: https://github.com/louislam/uptime-kuma/issues/268

Fix Telegram Bot Token displayed in notification setup view

---

ansible/roles/nginx/templates/nginx.conf

fix path for logging in nginx ansible role

FIX: [ansible]logging volume not working

---

src/languages/id-ID.js

Here's my pull request
- Changed from Sandi to Kata sandi in line 10

Fixed the grammar issue

---

server/notification-providers/gorush.js
server/notification.js
src/components/notifications/Gorush.vue
src/components/notifications/index.js
src/languages/en.js

Implement gorush notifications

---

server/notification-providers/techulus-push.js
server/notification.js
src/components/notifications/TechulusPush.vue
src/components/notifications/index.js
src/languages/en.js

Add support for new notification provider -> https://push.techulus.com

Add notification provider - Push

---

package.json

Hello, thank you for using this package. We published some updates and you might want to update your package version. : ) Thank you!
check-password-strength that supports additional symbols/special characters referenced from owasp list.
[PR reference](https://github.com/deanilvincent/check-password-strength/pull/60/files)
Version update of the check-password-strength from 2.0.3 to 2.0.5
Symbols:
Prior to 2.0.5: 
```
!@#$%^&_
```
2.0.5+: 
```
!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~]
```

check-password-strength new version update 2.0.5 

---

src/languages/hu.js

.HU lang update, should do lazy merge PR before new release.

fix: .hu lang

---

src/pages/StatusPage.vue

Closes #483
Also partially #443
This is a proposed change to update the favicon of the status page to the configured logo of the status page.
It will automatically update whenever the logo is changed.
Minimal change to the code, no new dependencies, or database/backend changes. Just using the favico.js library that was added recently for the badge counter.

feat: Favicon is updated based on satus page logo

---

src/languages/hu.js

fix: update hu lang

---

server/notification-providers/alerta.js

Fix "API key parameter 'undefined' is invalid".
Variable name: alertaapiKey => alertaApiKey

Fix "API key parameter 'undefined' is invalid"

---

extra/reset-password.js
server/database.js
server/proxy.js
server/server.js
server/socket-handlers/proxy-socket-handler.js
src/pages/EditMonitor.vue

Proxy Improvements

---

src/languages/en.js
src/languages/zh-CN.js

New translation for zh-CN

---

server/notification-providers/onebot.js
server/notification.js
src/components/notifications/OneBot.vue
src/components/notifications/index.js
src/languages/en.js
src/languages/zh-CN.js

Add OneBot HTTP notification service support to make it possiable to push notification via Tencent QQ

Add OneBot notification service

---

src/components/PingChart.vue

Fixes readability of dropdown menu hover, see screenshots.
Without this change:
With this change:

Fix readability of dropdown menu hover

---

server/notification-providers/pushdeer.js
server/notification.js
src/components/notifications/PushDeer.vue
src/components/notifications/Pushdeer.vue
src/components/notifications/index.js
src/languages/en.js

Add support for [pushdeer](http://www.pushdeer.com/) notifications.
notification setting:
Pushdeer Android client:

 Add support for Pushdeer notifications

---

src/components/PingChart.vue

Add simple function to save and restore the chart period option per monitor.
- User Interface

Feat: Save and restore chart period

---

server/server.js
server/util-server.js
src/pages/EditMonitor.vue

As titled. Don't know if there would be situations where the response message is unknown.
- Other

Feat: Allow MQTT successMessage to be optional

---

test/e2e.spec.js

Related to #1499 
This PR adds JSDoc comments for the `test/*` directory. For the full TODO list, see #1499
- Other

JSDoc for test/*

---

.github/workflows/auto-test.yml
package.json

Fix duplicated GitHub Actions comments for Pull Requests + shorter usage of Node matrix.
You can see new job here: https://github.com/louislam/uptime-kuma/runs/6167402233?check_suite_focus=true
- Other

Fix duplicated PR comments

---

.github/workflows/auto-test.yml

Addendum to https://github.com/louislam/uptime-kuma/commit/000cbeb0ce1921f36314ea904fcf5b23e61bd179
- Other

Fix actions/setup-node task name

---

src/components/CountUp.vue
src/components/Datetime.vue
src/components/Status.vue
src/components/Uptime.vue
src/pages/StatusPage.vue

Fix ESLint warnings and errors
- Other

Fix ESLint warnings and errors

---

server/notification-providers/discord.js

Fixes #1678 
- Improved Discord Notifications with Push Monitors
---

Improved Discord Notifications with Push Monitors

---

src/pages/EditMonitor.vue

Re #1636 
Adds default value to the sql server connection string field.
- New feature (non-breaking change which adds functionality) - change for beta

[beta] added default value for sql server connection string

---

src/pages/EditMonitor.vue

Fixes #1766
- Bug fix in beta (non-breaking change which fixes an issue)

[beta] workstation field should be text, not password

---

README.md

Adding links in Subreddit section as well as making the section look better.
Documentation
- Other

Fixing small Readme links.

---

server/notification-providers/alertnow.js
server/notification.js
src/components/notifications/AlertNow.vue
src/components/notifications/index.js

This will add the new notification type, AlertNow.
Also, I sort the notifications to make it more readable.

Feat: New Notification Type for AlertNow

---

server/routers/api-router.js

I added the label option to the status badges.
Fixes #1696

Added label to status badge

---

server/notification-providers/bark.js

👉 Delete this line if you have read and agree our pull request rules and guidelines: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma
Fixes #(issue)

Fix previously PR bug about Bark Notification

---

server/notification-providers/goalert.js
server/notification-providers/smsmanager.js
server/notification.js
src/components/notifications/SMSManager.vue
src/components/notifications/index.js
src/languages/cs-CZ.js

- I added support for notification via SMSManager
- SMSManager is local provider for sending SMS in Czech republic, but they have options send SMS through a lot of countries.

feat: Add support notification via SMSManager

---

server/notification-providers/serverchan.js
server/notification.js
src/components/notifications/ServerChan.vue
src/components/notifications/index.js

feat: Add ServerChan Notification support

---

server/notification-providers/teams.js

The filling of the URL field was incorrect previously. It has been updated to handle new monitor types.
Fixes #2009

Fixed alert features unnecessary URL field #2009

---

server/docker.js
server/model/monitor.js
server/socket-handlers/docker-socket-handler.js
src/components/DockerHostDialog.vue

Fix Docker container monitor not working in 1.18.1

---

README.md

Related to #2164
- Other
- This change requires a documentation update (Done)

New Demo Server

---

src/languages/id-ID.js

Fixes #(issue)
- Other
Please do not use any external image service. Instead, just paste in or drag and drop the …

Fix typo in id-ID language file

---

src/languages/id-ID.js

Fixes #(issue)
- Other
Please do not use any external image service. Instead, just paste in or drag and drop the …

fix typos in id lang

---

server/model/heartbeat.js
src/components/Datetime.vue

Fix 'dayjs' is never used warning

---

server/notification-providers/ntfy.js
src/components/notifications/Ntfy.vue
src/languages/en.js

Fixes #2135 by adding support for icon in the ntfy notification provider
- Other

Ntfy icon support

---

.gitignore
docker/dockerfile
extra/healthcheck.go
extra/healthcheck.js

Healthcheck using native / go-lang

---

src/languages/fr-FR.js

(fr) Fix typo

---

server/notification-providers/slack.js

This PR creates for solving the slack notification as the block is not working. I screenshot some images below.
- [] My code needed automated testing. I have added them (this is optional task)
Before change
After change

Slack notification block not working

---

src/components/TagsManager.vue

Fixes #2482
The creating duplicate tag form check should only set when no existing tag is selected.

Fix: Fix incorrect add tag form validation

---

server/notification-providers/pushover.js

Removed redundant title in Pushover notification

---

server/jobs/clear-old-data.js
src/components/settings/MonitorHistory.vue
src/languages/en.js
src/pages/Settings.vue

Previously, a retention period of less than 0 was permitted to be entered into the web interface. This led to an effectively infinite retention period. This PR prevents the user entering a negative retention period. It also allows for the retention period to be set to 0 for infinite retention if the user does so desire.
Fixes #2565

Fixed negative retention time values

---

src/languages/fr-FR.js

Signed-off-by: DimitriDR <dimitridroeck@gmail.com>
French localization updated.

Updating French localization

---

.github/workflows/auto-test.yml
config/cypress.frontend.config.js
package.json
test/cypress/unit/i18n.spec.js

Fixes #2580
I added cypress unit tests as I could not get jest to work (SyntaxError: Cannot use import statement outside a module) as per the [cypress unit test recipe](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/unit-testing__application-code).
I will update the documentation if ths solution is validated. …

Add frontend unit tests

---

server/notification-providers/pushover.js

Fixes #(issue)
- Other
- [ x] My code follows the style guidelines of this project
- [ x] I ran ESLint and other linters for modified files
- [ x] I have performed a self-review of my own code and tested it
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings
- [ x] My code needed automated testing. I have added them (this is optional task)
Please do …

Removed superflous 'Message' prefix from Pushover

---

server/routers/api-router.js

Folllow up on #2525, small code cleanup.
- Other

Chore: Use constants instead of int

---

src/lang/en.json
src/pages/ManageMaintenance.vue

Added missing keys for translation
Fixes #(issue)
- Other

Add keys for translation

---

README.md

Update README: Add npm as requirement

---

src/pages/StatusPage.vue

adds markdown support for status page description
Fixes https://github.com/louislam/uptime-kuma/issues/2365
Complements https://github.com/louislam/uptime-kuma/pull/2570 and https://github.com/louislam/uptime-kuma/pull/2570#issuecomment-1426866318

add markdown support for description

---

server/routers/api-router.js
server/routers/status-page-router.js
server/util-server.js

Fixes #2746
Since we are generically catching all errors, we don't know if 403 is a suitable code anyway. Or I guess we can also add a parameter to the function to optionally specify the Status Code.

Feat: Use error message to detect and set status code

---

server/model/monitor.js

see https://github.com/louislam/uptime-kuma/issues/2785
sorted tags on dashboard list

sorted tags on dashboard

---

server/socket-handlers/general-socket-handler.js

Fixes #2833 (first issue). Seems like `getGameList` is missing a return in the if branch.

Fix: getGameList returns nothing on first run

---

src/components/TagEditDialog.vue
src/components/settings/Tags.vue

Feat: Add "Add New Tag" button in settings

---

package-lock.json
package.json

Merge 1.20.x to master

---

server/notification-providers/pagertree.js
server/notification.js
src/components/notifications/PagerTree.vue
src/components/notifications/index.js
src/lang/en.json

Adds [PagerTree](https://pagertree.com) Notification Provider
- User interface (UI) => Adds PagerTree Notification Provider Component (Vue)
- New feature (non-breaking change which adds functionality) => Adds PagerTree Notification Provider (Server)
None

Adds PagerTree Notification Provider

---

src/pages/EditMonitor.vue

Fixes assigning tags when cloning a monitor.

Fix: assign tags when cloning monitor

---

src/i18n.js

Added Hebrew (he_IL) support

---

src/i18n.js

Add new Language
- Add new Language

Add new Language: Urdu

---

server/util-server.js

Fix: Disconnect redis after ping

---

server/uptime-kuma-server.js

Add supported for encrypted private key in the HTTPS server config.

Chore: Add support for encrypted SSL-key

---

src/components/APIKeyDialog.vue

Fixes console error after creating API key. No functional impact since the error line is the last line in the function.

Fix: Add missing clearForm func.

---

server/model/monitor.js

Fixes #2899. There is no point sending if a smaller target days has already been notified.

Fix: Check for TLS expiry notified days smaller than target

---

server/routers/api-router.js

Fixes #2974
- Other
Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be …

Fix: Allow status badge with empty label

---

server/routers/api-router.js

Fix: Apply toPrecision as last step

---

.github/workflows/json-yaml-validate.yml

There are [51](https://github.com/GrantBirki/uptime-kuma/actions/runs/4526725141/jobs/7972085215#step:3:63) json files (as of today) in this repository. There are currently no CI jobs that validate these files in a quick and efficient manner. This pull request adds a new CI job that will run and validate all yaml / json files in this repository to ensure they are valid via CI tests.
This new CI job takes about ~5 seconds to run and can properly ensure all json / yaml files are validated with ease. It will also create a comment on pull requests with validation errors if any should arise from contributors
- Other (CI)

GitHub Actions - Validate json / yaml files 📁 

---

.github/config/exclude.txt
.github/workflows/json-yaml-validate.yml

I published a new version of the json-yaml-validate Action today ([`v1.3.0`](https://github.com/GrantBirki/json-yaml-validate/releases/tag/v1.3.0)) to allow the ease of management through an `exclude.txt` file should you need to exclude any files from validation in the future. This file follows the same syntax as a `.gitignore` file. Enjoy!
> CI update only
- Other

:fishsticks: Upgrade json-yaml-validate

---

server/socket-handlers/status-page-socket-handler.js
src/mixins/theme.js
src/pages/StatusPage.vue

Feat: Support auto theme in status pages

---

package.json

Fixes a type in package.json
- Other
Please do not use any external image service. Instead, just paste in or drag and drop the image here, …

🐛 fix(package.json): correct typo in deploy-demo-server script name

---

server/notification-providers/mattermost.js

Improve mattermost notifications.
- use icons for notification icon
- set variables for iconEmoji and use them in `mattermostdata` instead of creating two different variable for up and down notifications
- limit the usage of attachment fields and remove duplicate information
- Other (improve notification provider)

Improve mattermost notifications

---

src/components/settings/Tags.vue

Margins were too big on mobile.
|before|after|
|------|-----|
|![Screen Shot 2023-03-31 at 21 47 02](https://user-images.githubusercontent.com/3271800/229140080-179a41a9-aa03-43a4-b1c4-bd5d5385655d.png)|![Screen Shot 2023-03-31 at 21 52 02](https://user-images.githubusercontent.com/3271800/229140126-a0dd9489-c300-4b40-a967-f835c1499404.png)|

UI: Improve Tags settings design on mobile

---

src/pages/Details.vue

Fixes #(issue)
- It said "TCP Ping" when I added TCP Port monitor, fix that to say "TCP Port".
- This annoyed me: 
- Fix:

Fix typo in dashboard TCP Port items

---

server/notification-providers/dingding.js

According to https://github.com/louislam/uptime-kuma/issues/2910#issuecomment-1501743885 , let the notification to dingding use the server timezone
- Other

feat: show time as server timezone in dingding notification

---

package-lock.json

updates legacy dependency!
- Update dependencies

:rocket: Update legacy deps

---

src/pages/Details.vue

General reductions of margins and font-size to better fit mobile.
|before|after|
|------|-----|
|![Screen Shot 2023-04-11 at 21 17 28](https://user-images.githubusercontent.com/3271800/231175815-2b1a59dd-d081-4f90-8016-fa5c111f7895.png)|![Screen Shot 2023-04-11 at 21 16 51](https://user-images.githubusercontent.com/3271800/231175725-f9f72d75-15e9-4ced-a174-0d1a0a075a96.png)|
|![Screen Shot …

UI: Improve monitor page layout on mobile

---

server/util-server.js

Fixes #3020
Searched around and there seems to be no way to determine the state of the connection without sending something, so this should be a good enough solution.

Fix: Try to close mysql connection properly

---

src/pages/NotFound.vue

Add translation for Not Found page

---

src/lang/de-CH.json
src/lang/de-DE.json
src/lang/en.json

I added the three keys noticed by @DevItq noted in #3244, that "Home" is also not translatable => This key is added.

Chore: Added a translation key for "Home"

---

server/auth.js

Address missing logs for failed auth attempts in #3307.
- Other

Chore: Add logging for failed auth

---

extra/exe-builder/FodyWeavers.xml
extra/exe-builder/Properties/AssemblyInfo.cs

Fix #3142, after added more assembly info, it seems better. But there are still 5 false positive detection. 
Directions:

[exe] Try to deal with the false positive issue

---

src/mixins/theme.js

Fix auto theme for status pages on custom domains

---

server/database.js

Fixes lint warning
- Other
Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it …

:bug: fix lint warning

---

src/assets/multiselect.scss

Fixes multi-select blocked by the bottom bar in Edit Maintenance.

Fix: Multiselect blocked by bottom bar

---

server/notification-providers/smsc.js
server/notification.js
src/components/NotificationDialog.vue
src/components/notifications/SMSC.vue
src/components/notifications/index.js

By @FlatronBuda, closes #3334.

Add SMSC (СМСЦентр) provider notification

---

src/components/TagEditDialog.vue

The delete button was not hidden correctly, don't now why I didn't catch this.

Fix: Hide delete button in Settings -> Create New Tag

---

.github/ISSUE_TEMPLATE/ask-for-help.yaml

Fixes the confusion in #3426 in the future
- Other

Fixed `Replit` not being mentioned in the help template

---

README.md
package-lock.json
package.json
server/server.js

Support Node.js 20 again

---

.devcontainer/README.md
.devcontainer/devcontainer.json
config/vite.config.js
package.json
src/mixins/public.js
src/mixins/socket.js
src/util-frontend.js

Add support for Codespaces

---

.devcontainer/devcontainer.json
config/vite.config.js
src/util-frontend.js

Suggested by @Erb3
https://github.com/louislam/uptime-kuma/pull/3432#discussion_r1265120809

Fix codespace url 

---

.devcontainer/README.md

Fixed a few typos and gramar mistakes in the Codespaces docs
- Other
- My code needed automated testing. I have added them (this is optional task)

Chore: Fixed a few typos and gramar mistakes in the Codespaces docs

---

src/assets/app.scss

After #3312, the monitor list is now too long.

Fix: Update monitor-list height to accomodate filters

---

src/components/notifications/Mattermost.vue

Fix dead link to the Mattermost webhook docs
- Other

Mattermost: update dead docs link

---

server/notification-providers/smtp.js

Fix: SMTP notification "Ignore TLS Error" option (#2999)

---

docker/debian-base.dockerfile
docker/etc/nscd.conf
docker/etc/sudoers
server/server.js
server/uptime-kuma-server.js

Built-in nscd into the docker image (a better dns caching service)

---

server/notification-providers/pushdeer.js
src/components/notifications/PushDeer.vue
src/lang/en.json

**The original PR is #3459.**
**Sorry I mistakenly deleted the fork repository and causing the original PR to close when I cleaned up my account.**
Fixes #3449 

[reopened] feat: allow the user to configure PushDeer Server URL

---

README.md

The main focus of this pull request is to enhance the README file, making it more informative, user-friendly, and visually appealing. I believe that clear and comprehensive documentation plays a crucial role in fostering the project's growth and encouraging new contributors
- Other

🐛 fix(README.md): fix readme

---

CONTRIBUTING.md
README.md

@M1CK431 noticed that the link in our contribution guide explaining translation is broken.
This PR addresses this concern and fixes a minor few gramar-peves I noticed.
Related https://github.com/louislam/uptime-kuma/issues/3507

Chore: Updated translation contributing guide

---

babel.config.js
package-lock.json
package.json
server/database.js
server/util-server.js
test/backend.spec.js

After this commit, the test is now failed.
https://github.com/louislam/uptime-kuma/commit/67b1974718c287f01254c01b814ae99ba32c7cf0
I have no idea what is happening.

Fix test failed

---

src/components/MonitorList.vue

`filtersActive` should be in `computed` instead of `watch`.

Fix: filtersActive placed incorrectly

---

server/server.js
server/util-server.js

Check type of status code range to ensure it is a string before we start running string operations on it.
Fixes #3520

Fixed #3520 Validate accepted status codes type

---

CONTRIBUTING.md

In https://github.com/louislam/uptime-kuma/issues/3564 a contributor was unclear about this part of the contributing guide.
This PR rephrases this part to make shure that other contributors don't shy away from proposing such changes, if they do their duediligance
- This change is a documentation update …

Docs: Rephrased dependency-updates in the contributing guide

---

src/pages/Setup.vue

[As requested by @CommanderStorm](https://github.com/M1CK431/uptime-kuma/pull/1#discussion_r1289940094), I translate Setup page fields placeholders. I well know it's not visible at all on the page because only the "floating label" is displayed but I guess it might be useful for accessibility 🤷🏼‍♂️ 
(including JSDoc for methods) => not relevant in this specific case
As explained in description, there is no visual change.

[webapp] Setup: translate fields placeholders

---

src/components/MonitorListFilter.vue

bug: fixed the curser being a pointer if hovering above the `dropdown-item`'s

---

src/components/Login.vue
src/components/TwoFADialog.vue
src/components/settings/Security.vue

This adds a few missing attributes to help password managers.
* `autocomplete="username"`
* `autocomplete="current-password"`
* `autocomplete="new-password"`
* `autocomplete="one-time-code"`
* `required` where it was previously missing

Passwordmanager friendly inputs

---

server/model/monitor.js

Fixes #3608
- Save all returned values of `PTR` records
- Make sure `dnsMessage` is defined

Fix: Improve dnsMessage handling

---

src/components/MonitorListFilterDropdown.vue

Fixes #3618
|before|after|
|------|-----|
|![image](https://github.com/louislam/uptime-kuma/assets/3271800/cee2139c-11e1-4d9f-96e2-d922e5151f00)|![image](https://github.com/louislam/uptime-kuma/assets/3271800/a911ffea-fe52-4f2a-9317-b042f85bc6a7)|

Fix: Filters Focus & styling on safari

---

server/server.js

Fixes #3619
- [] I have performed a self-review of my own code and tested it

Fix: Remove legacy unused tags cleanup

---

package-lock.json
server/database.js
server/embedded-mariadb.js
server/model/monitor.js
server/setup-database.js
server/uptime-calculator.js
server/utils/array-with-key.js
server/utils/limit-queue.js
src/components/settings/Notifications.vue
src/layouts/Layout.vue
test/backend-test/test-uptime-calculator.js

This PR fixes 
- a few issues relating to the usage of jsdoc where `npm run lint complaints`
- That the `package-lock.json` file has the wrong version
@Computroniks could you give this an additional review if I missed something/ am using jsdoc badly?
- Other

chore(jsdoc):Linting fixes

---

server/server.js

Fix: Missing await for monitor.isActive()

---

.github/workflows/auto-test.yml

As the `prevent-file-changes` is in separate file this needs to be removed and preventing workflows to run properly
- Bug fix

🐛 fix: AutoTest workflow

---

src/pages/StatusPage.vue

Fix: Disable Status page Save button on submit

---

server/model/monitor.js

Enable status page certificate expiry badge for all HTTP(s) monitors

---

README.md

The correct link includes a `-2`
Fixes #3807

chore:fixed the portable link in the readme

---

server/model/monitor.js
server/routers/api-router.js
server/routers/status-page-router.js

Fixes build warnings in GH Actions.
- Other

fix: Fix build warnings

---

docker/dockerfile

This label can be used to fetch more information about this image. For example Renovate uses this label to get the changelog of a specific version: https://docs.renovatebot.com/modules/datasource/docker/
- Other

Add LABEL to Docker image

---

.devcontainer/README.md
.github/ISSUE_TEMPLATE/security.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md
db/knex_migrations/README.md
extra/push-examples/typescript-fetch/README.md
src/lang/README.md
test/backend-test/README.md

Fix markdownlint warnings
- Other

fix: Markdownlint warnings

---

src/components/MonitorList.vue

Missing callbacks for batch pause/resume causes "Callback is not a function" on the server.

Fix: Missing callbacks for batch pause/resume

---

src/pages/StatusPage.vue

Revert "Fix: Disable status page saving before getData"

---

server/model/user.js
server/server.js
server/util-server.js

Resolves lint warnings breaking the builds

🐛 fix: lint warnings & errors

---

.github/workflows/codeql-analysis.yml

⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
Add new codeql workflow to analyze code and it will run on master & 1.23.X branch.
- Other

🚀 Add CodeQL Action to analyze code

---

src/pages/Entry.vue

Fixes the entry page setting handling when the front-end is in Dev-mode. I'm guessing the relevant code was not updated to handling multiple status pages.
- Other

Chore: Fix entry page handling in Dev mode

---

db/patch-fix-kafka-producer-booleans.sql
server/database.js
server/model/monitor.js
server/server.js
src/pages/EditMonitor.vue

Fix field types in database and converting it to boolean just like other boolean fields
newly added migrations should be okay since we where storing data in 0 and 1
Fixes https://github.com/louislam/uptime-kuma/issues/3760

🐛 fix: boolean fields in kafka producer monitor

---

src/i18n.js

Add Uzbek language

---

server/model/monitor.js
server/util-server.js

Follow up #3961. Forget to rebase to 1.23.X

Fix/axios abort signal for 1.23.X

---

server/model/monitor.js
server/util-server.js

See https://github.com/louislam/uptime-kuma/pull/3961#issuecomment-1804149144 for more details

Should be an ulitmate fix for request timeout issue

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md
SECURITY.md

~~Fixes #(issue)~~
This PR does not fix an issue.
- Other

feat: grammar fixes

---

db/patch-timeout.sql
server/database.js
server/model/monitor.js

Should be a final ulitmate fix for request timeout issue

---

src/components/PublicGroupList.vue

fix: Clickable link monitors aren't underlined when editing status page #3795

---

server/model/monitor.js
server/util-server.js

+10 seconds for Abort signal, so axios should use the original timeout first.

+10 seconds for Abort signal

---

server/util-server.js

Original pr: #4083
I tried to rebase to the 1.23.X branch
By @mvaled

Close the client postgresql connection after rejection.

---

server/model/monitor.js
server/uptime-kuma-server.js

Reverts louislam/uptime-kuma#3952
I think I was too confident to add this. It actually creates some issues. I pull it out first in the next release, maybe fix it later.

Revert "Restart running monitors if no heartbeat"

---

server/monitor-types/tailscale-ping.js
server/socket-handlers/general-socket-handler.js
src/util.js
src/util.ts

Rewrite Tailscale ping using spawnSync

---

server/docker.js

Fixes #2132. Add timeout for `testDockerHost()` function in case connection cannot be established.

Fix: Add timeout to testDockerHost

---

server/notification-providers/mattermost.js

Fixes #3798
- Other
Before:
After:

monitor path as a notification title mattermost

---

package-lock.json
package.json

Update gamedig from ~4.1.0 to ^4.2.0

---

server/setup-database.js

Close #4021
Details: https://github.com/louislam/uptime-kuma/issues/4021#issuecomment-1807737839

Fix UPTIME_KUMA_DB_NAME issue

---

server/server.js

Fixes typo for function name `disconnectAllSocketClients`.

Fix: typo for `disconnectAllSocketClients`

---

server/monitor-types/tailscale-ping.js
server/notification-providers/apprise.js

Fix #4228
Not sure why it was working without encoding, but now doesn't.

Fix Async child process output issue

---

src/components/CountUp.vue

Supersedes #3930
- No change if value is integer
- If value is less than 1, display "<1"
- Otherwise, round value to 2 decimal places to be consistent with the other values.

Feat: `Countup` display fixed value

---

server/util-server.js

Fix incorrect ping log

---

src/pages/ManageMaintenance.vue

- Add margins and increase width to 100% in mobile view
- Remove inconsistent height of buttons in normal view
- Switch delete button to `btn-normal`
|before|after|
|----|----|
|![Screenshot 2024-01-22 170742](https://github.com/louislam/uptime-kuma/assets/3271800/7d172c2d-22c1-405f-80c9-637a14f35ab1)|![Screenshot 2024-01-22 170636](https://github.com/louislam/uptime-kuma/assets/3271800/bb334572-9b18-4450-85f4-8c95aa90b2c …

UI: Improve maintenace actions design

---

src/i18n.js

- [X ] I have read and understand the pull request rules.
Added Irish (Gaeilge) language
https://weblate.kuma.pet/projects/uptime-kuma/uptime-kuma/ga/
Language code: ga
- Other

Added Irish language

---

.github/workflows/stale-bot.yml
extra/close-incorrect-issue.js

I have reworked some of the comments we leave on issues:
- The incorrect issue template comment did not include a "Call to action" and did not properly communicate why these templates are nessesary
- `Stale`-Issues
- I think the current staleness interval of `2` days is very short (some people don't read mails every day..) => changing this to min. `7` days lessens this
- Given how much activity we get in stale `help`-issues, I think we can start closing the earlier than `90` days => have …

`Stale`, incorrect issue template and `cannot-reproduce` Comments

---

config/vite.config.js
package-lock.json
package.json

It is much faster and better than the browser plugin.
Read more: https://devtools-next.vuejs.org/guide/features#features
```
Vue DevTools: Open http://localhost:3000/__devtools__/ as a separate window
```

Add Vue DevTools

---

CONTRIBUTING.md

This PR addresses a few issues I had when reading the contribution guide.
Among them:
- made sure that all technical terms have he proper code-block
- refactoring the maintainer-only procedures to be more compact by including `<details>` blocks
- added a rationale why a discussion is prefered
- added a section on `I'd like to work on an issue. How do I do that?`
Refactoring `Can I create a pull request for Uptime Kuma?` to give more actionable advice on how to create new monitoring/notification …

More readable Contribution guide

---

CONTRIBUTING.md

This PR refactors `Can I create a pull request for Uptime Kuma?`:
- to give more actionable advice on how to create new monitoring/notification types
- what types of PRs exist and how they should be handled
- how they can be merged. **⇐ This one might be controversial. We can obviously revert this change ^^**
Related to https://github.com/louislam/uptime-kuma/pull/4525
- Other
| Before | After | …

Refactored the `Can I create a pull request for Uptime Kuma` section

---

src/components/notifications/Line.vue
src/lang/en.json

Fixes #4526 
This is just some string changes to reflect how the LINE dev environment looks now
- [ N/A] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)

Updated strings for `LINE Messenger` as changed in their developer portal

---

server/server.js

Based on a disucssion in https://github.com/louislam/uptime-kuma/pull/4574#discussion_r1527962537
- Other

made sure to use `Promise.allSettled` instead of sleeping for 500ms after login

---

.github/workflows/auto-test.yml

`1.23.X` verison of #4557.
- Other

Fix: Fix CI on Windows Runner [1.23.X]

---

server/model/monitor.js
server/uptime-calculator.js
src/mixins/socket.js
src/pages/Details.vue

fix some typos in comments
- Breaking change (a fix or feature that would cause existing functionality to not work as expected)
- Other
Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded …

chore: fix some typos in comments

---

README.md

proxy is not spelled like I did
- Other
-

Fixed a typo introduced in #3836

---

server/socket-handlers/status-page-socket-handler.js

Fixes https://github.com/louislam/uptime-kuma/issues/4749

chore: fixed a typo for internal, unused part of the file upload icon for status page

---

src/pages/EditMonitor.vue

Fixes an issue we missed in https://github.com/louislam/uptime-kuma/pull/3857

made sure that json-query for the mqtt monitor is translated properly

---

src/components/notifications/SMSPartner.vue

During https://github.com/louislam/uptime-kuma/pull/4769#discussion_r1608516864 I made a typo (I meant `tag="div"` not `as="div"`)

Fixed `smspartner` not having fully working translations

---

docker/debian-base.dockerfile
package-lock.json
package.json

And install Apprise from the deb file.
Fix #4867
Thanks @p00rt for pointing out the issue.

Drop out the testing repo from apt

---

CONTRIBUTING.md

docs: fixed typo in the contribution guide

---

server/server.js
server/socket-handlers/database-socket-handler.js
server/socket-handlers/general-socket-handler.js

I noticed that not all our socket handlers have names or docstrings. This PR fixes this 
- Other

made sure that the socket handlers have consitent names

---

server/notification-providers/wpush.js
server/notification.js
src/components/NotificationDialog.vue
src/components/notifications/WPush.vue
src/components/notifications/index.js

Fixes #(issue)
- 
test : 
down: 
up:

Add WPush Notification Provider

---

config/playwright.config.js
src/components/MonitorList.vue
src/components/PublicGroupList.vue
src/components/TagsManager.vue
src/pages/AddStatusPage.vue
src/pages/EditMonitor.vue
src/pages/StatusPage.vue
test/e2e/specs/example.spec.js
test/e2e/specs/status-page.spec.js

Adds an E2E test for Status pages.
This E2E test ensures a status page can be created and edited. It tests most of the editable fields.
Items not yet being tested:
- Show certificate expiry
- Domain names _(haven't thought about how to go about testing this)_
- Other
None

Status Page E2E spec

---

config/vite.config.js

Fix #5157 and cleanup some devcontainer code

---

server/notification-providers/wecom.js

Fix notice title definition issue.

Fix: Resolve notice title definition issue and add newline between title and content in notification

---

server/model/monitor.js
server/prometheus.js

Reverts louislam/uptime-kuma#4704
Fix #5096

Revert "Extend Prometheus Labels to include tags (requires restart for NEW labels on the monitor to be visible)"

---

server/notification-providers/discord.js
server/notification-providers/notification-provider.js
server/notification-providers/sevenio.js
server/notification-providers/signl4.js
server/notification-providers/slack.js
server/notification-providers/smtp.js
server/notification-providers/squadcast.js
server/notification-providers/teams.js
server/notification-providers/zoho-cliq.js

While working on another fix, I noticed this small typo. Thank you for your work on Uptime Kuma :)
- Other

fix: misspelling of 'address'

---

CONTRIBUTING.md

Some grammatical improvements in the CONTRIBUTING.md file that I noticed while reading through to set up my local development environment to check another issue.

docs: grammatical improvements in contribution guide

---

src/components/PublicGroupList.vue

Reverts louislam/uptime-kuma#4376 as there is a bit of a visual bug which I overlooked
Thanks @candies404 for reporting it

Revert "Extend length of status bars in status page"

---

server/notification-providers/serverchan.js

Update ServerChan server api url to compatiblewith the latest version 

Update API URL to compatible with the latest version of ServerChan

---

.github/workflows/json-yaml-validate.yml
extra/check-lang-json.js
src/lang/en.json

Follow up #5232 
JSON files now must be identical after re-stringify with `JSON.stringify(data, null, 4)`.

Verify language json file format

---

docker/dockerfile

Fix: the rootless user put in the wrong place

---

extra/release/beta.mjs
extra/release/final.mjs
extra/release/lib.mjs
extra/release/nightly.mjs

Publish docker images to ghcr.io

---

src/pages/EditMonitor.vue

see https://github.com/louislam/uptime-kuma/issues/5323
Fixes #(issue)

fix(notification): #5323 fix EditMonitor.vue useToast error

---

package-lock.json
server/database.js

Fix: [MariaDB] Unable to clean up heartbeat data

---

extra/release/lib.mjs

Follow up #5311
- Breaking change (a fix or feature that would cause existing functionality to not work as expected)
- Other

Fix release script issue

---

src/components/TagsManager.vue

Fixes #5442 (another fix has been made regarding comments on this issue, aka https://github.com/louislam/uptime-kuma/issues/5442#issuecomment-2556748007. I suggest you to check the video to see what was happening).
This was happening from a while, and was related to an invalid variable (using `tag.id` instead of `tag.tag_id`). Works fine for existing tags and new tags.

Fix monitor tags deletion

---

server/notification-providers/aliyun-sms.js

Small modifications:
The time in the AliyunSMS is UTC+0, so I changed it to local time.
Fixes #(issue)

Modify the "Time" in the AliyunSMS to local time.

---

.github/ISSUE_TEMPLATE/security_issue.yml

- #5593
@CommanderStorm, I had forgotten that guests can't assign someone without the proper permissions in GitHub. Therefore, I have adjusted the security issue template so that Louis Lam still receives a notification when there is a new security issue.
My apologies for the inconvenience.
---
https://github.com/louislam/uptime-kuma/security/advisories/GHSA-8h5r-7t6l-q3kz
---
**Note:**
- There is no space between the "@" symbol and "louislam" in the security issue. I don’t want to unnecessarily …

Fix: Updated security issue template

---

package.json

Update package.json to check-out the latest stable release ([v1.23.16](https://github.com/louislam/uptime-kuma/releases/tag/1.23.16)) when users check-out the `main` branch, using the steps explain in your own README:
```sh
git clone https://github.com/louislam/uptime-kuma.git
cd uptime-kuma
npm run setup
```

Update to latest stable version on the main branch

---

.github/ISSUE_TEMPLATE/feature_request.yml
.github/PULL_REQUEST_TEMPLATE.md

Fixed: Markdown hyperlinks in feature_request.yml and PULL_REQUEST_TEMPLATE.md

---

package-lock.json

fix: align package-lock.json version with package.json

---

src/components/Tag.vue

Auto Fix by GitHub Copilot. Just want to try out the new feature "Code with Copilot Agent".
Not verified yet.
Fix #5745

Fix #5745: Some labels without value still show a 'null' value 

---

extra/reset-password.js

- Please provide a detailed explanation here.
I used `passwordStrength` to check the password strength in `extra/reset-password.js` , just like in `server/server.js`
- Prevent the use of weak passwords when resetting passwords using the CLI. 
- Relates to #5787
- Resolves #5787
- Fixes #5787
| Event              | Before                | After                |
| ------------------ | --------------------- | -------------------- |
| Testing            | ![image](https://github.com/user-attachments/assets/248fce50-ce31-49ca-a868-d9a2f77712e8) | ![image](https://github.com/user-attachments/assets/c8f44544-c386-4f7e-855f-c145d0ce2e9c)|

fix: Check password strength when resetting the password in CLI

---

server/notification-providers/sms-planet.js
server/notification.js
src/components/NotificationDialog.vue
src/components/notifications/SMSPlanet.vue
src/components/notifications/index.js
src/lang/en.json
src/lang/pl.json

- It solves the lack of SMSPlanet integration, giving users—especially in Poland—an affordable and easy way to send SMS alerts.
- It introduces a new notification provider for SMSPlanet, including configuration options and sending SMS through their API.

feat: Support SMSPlanet notification provider

---

server/notification-providers/spugpush.js
server/notification.js
src/components/NotificationDialog.vue
src/components/notifications/SpugPush.vue
src/components/notifications/index.js
src/lang/en.json

This pull request adds ‌SpugPush‌ as a new notification provider for Uptime Kuma.
- **What problem does this pull request address?‌**
- Adds support for SpugPush notifications, allowing users to receive alerts through Spug's notification system.
‌
- **What features or functionality does this pull request introduce or enhance?‌**
- Implements a new notification provider (SpugPush) with standard notification features.
- **Screenshot**

Add SpugPush notification provider

---

server/notification-providers/spugpush.js

Update SpugPush notification payload

---

server/notification-providers/notifery.js
server/notification.js
src/components/NotificationDialog.vue
src/components/notifications/Notifery.vue
src/components/notifications/index.js

- Adding a non-existing notification provider.
- Adding support for notification provider [Notifery.com](https://www.notifery.com)

feat: add notification provider Notifery

---

server/routers/api-router.js

Fix monitor reference in push notification logic

---

server/routers/api-router.js

Fix: [Push Monitor] Send notifications during maintenance period

---

package.json
src/util.js
src/util.ts
tsconfig-backend.json
tsconfig.json

Fix #5868
It seems that sharing tsconfig.json for both frontend and backend is a bit problematic now. Split into two tsconfig.json for more clearer.
Manual OK:

Fix: Update TypeScript configuration and refactor imports

---

server/model/maintenance.js
server/notification-providers/discord.js
src/pages/EditMaintenance.vue

Fix invalid maintenance date

---

server/model/maintenance.js

Ensure maintenance are always runned at the right moment

---

server/auth.js
server/model/user.js
server/password-hash.js
server/server.js
server/socket-handlers/api-key-socket-handler.js
server/util-server.js

Description see: https://github.com/louislam/uptime-kuma/pull/5924
It should be the last one of `[Eliminate Blocking]` series.

[Eliminate Blocking] User related

---

server/socket-handlers/general-socket-handler.js

[Eliminate Blocking] Push example

---

.github/ISSUE_TEMPLATE/ask_for_help.yml
.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/security_issue.yml
.github/PULL_REQUEST_TEMPLATE.md

chore: remove fluff from PR-template

---

.github/workflows/pr-reply.yml

The main purpose of this pr is trying to show the `npx kuma-pr <PR REPO, YOU CAN COPY>` command in each pr.
Feel free to suggest a better message.

Auto reply to PRs

---

server/docker.js
server/model/monitor.js
server/util-server.js

Description see: https://github.com/louislam/uptime-kuma/pull/5924

[Eliminate Blocking] Docker monitor

---

CONTRIBUTING.md
extra/close-incorrect-issue.js
server/database.js
server/notification-providers/flashduty.js
server/notification-providers/pushdeer.js
test/backend-test/test-mqtt.js

</p>
We kindly ask you to refrain from pinging maintainers unless absolutely necessary. Pings are for critical/urgent pull requests that require immediate attention.
</p>
</details>
fix some minor issues in the comments
- Please provide a detailed explanation here.
- Please provide a …

chore: fix typos in code comments

---

server/model/monitor.js
server/notification-providers/promosms.js
server/socket-handlers/api-key-socket-handler.js
server/uptime-calculator.js

</p>
We kindly ask you to refrain from pinging maintainers unless absolutely necessary. Pings are for critical/urgent pull requests that require immediate attention.
</p>
</details>
fix some minor issues in comments
- Please provide a detailed explanation here.
- Please provide a detailed …

chore: fix some minor issues in comments

---

package-lock.json
package.json
server/notification-providers/notification-provider.js

- Replace proxy-agent due to vm2 vulnerability. raised in PR https://github.com/louislam/uptime-kuma/pull/6125
- Replace proxy agent due to vm2 vulnerability in notification providers.
- Provide additional details here.

fix: Replace proxy-agent due to vm2 vulnerability
