louislam/uptime-kuma

server/notification.js
server/server.js
src/util-frontend.js

Differences between `console.log()`, `console.info()` and `console.error()` (Firefox and Chrome):

Improve printing to console

---

src/mixins/socket.js

We have better ways to see if we are in development env than adding local storage key to every web browser while testing and developing...
Related: https://github.com/louislam/uptime-kuma/issues/80

Use `NODE_ENV` from Express and Socket.IO

---

server/model/monitor.js

I'm terribly sorry, it looks like I set the parenthesis wrong when updating the notification rule.
With this the PR previousBeat definition check should pass.
This somehow eluded me in testing, as it affects the creation of new monitors only.
This fixes my changes in #86

Fix parenthesis mistake in notification checker (fixes #86)

---

src/components/Status.vue

On my screen, the width of the pill is still too narrow if the status is Pending. Increasing its width should fix this.
Browser: Firefox 90.0.2
OS: Windows 10 21H1 19043.1110

Fix: Increase width of status pill

---

server/server.js

Here are my findings to #159:
`end()` is not the recommended way to send a response, because it
- doesn't set the content-type,
- doesn't set the E-Tag, which may break caching on proxy
using `send()` should revert back to the previous correct behavior.

Fix: set content-type in response (#159)

---

src/pages/Settings.vue

The theme switch currently uses dark font on light theme, which is not consistent with other buttons.
Before:
After:

Fix: unify styling of theme switch btn

---

src/pages/Details.vue

As mentioned in #203 i fixed the function buttons on the details site.
I tried to keep the code simple and small without changing the html itself.
Up to 550px it'll look like this:
and up to 400px it'll be like this:

Fixed function buttons for smaller screens

---

src/components/PingChart.vue

- Use 24-Hour format display for now
- Increase padding to reduce label density
- Use "ticks" bounds to show axis ticks at the end

Fix: Improve Chart axis, use 24Hr format

---

src/components/HeartbeatBar.vue

- Add formatted time to tooltip of each beat. (#224)
- Add `required` to props `monitorId`
- Remove the unwanted side-effect in computed. Not sure if `beforeMount` is a good use of this but it seems to work fine.

Feat: Add time to beat tooltip, misc. fixes

---

src/components/PingChart.vue
src/pages/Details.vue

Make the chart bigger and responsive so it's at least readable on mobile.
| Before | After |
| ------ | ----- |
|![Screen Shot 2021-08-18 at 12 25 28](https://user-images.githubusercontent.com/3271800/129836831-a05f2647-6fcf-428c-9d02-58d1abb9e542.png)|![Screen Shot 2021-08-18 at 12 23 25](https://user-images.githubusercontent.com/3271800/129836679-fd3afc9f-275f-46fd-976a-6a61ecb845f9.png)|

Fix: Improve chart styling on mobile

---

package.json

Add lint commands which will produce js and style lint results to cli. This improves the usability of linting since Code Editor linting usually only works on open files.

Proj: Add npm lint commands

---

db/patch7.sql
db/patch8.sql
server/database.js
server/model/monitor.js
src/languages/de-DE.js
src/languages/en.js
src/pages/Details.vue

The latest DNS result will now be shown in the `Details.vue`, see example:
I also added the translation for the pause monitor confirmation.
**New i18n keys:**
`Last Result`
`pauseMonitorMsg`
**Example:** 
If it will be merged, it has to be before 1.5.0 gets released, since it'll further modify the `patch7.sql`

[Before 1.5.0] Show latest dns result in Details.vue

---

src/languages/fr-FR.js
src/main.js

Update few words and file name

---

dockerfile-debian

* Migrate from **node:14-bullseye** to **node:14-bullseye-slim** image.
* Remove unnecessary package installation.
* Apprise publishes a Python wheel for Debian distributions, which allows for removing the installation of development tools (g++, make) and python libraries via apt-get.
* Decreases by **51%** the uncompressed Docker image size from **1.31 GB** to **639 MB**.
Testing:
* Built image locally using Ubuntu Focal 20.04 LTS
* Started the Docker container and added 3 monitors (HTTPS, PING, DNS).
* I have no way of testing this for ARM.
Screenshot:

Debian Dockerfile refactoring and improvements

---

src/components/HiddenInput.vue
src/components/NotificationDialog.vue
src/icon.js

As mentioned in this [Card-68196873](https://github.com/louislam/uptime-kuma/projects/1#card-68196873) i added a new component with the ability to show and hide the input, see examples.
I also already changed the inputs for sensitive data like bot tokens in the `NotificationDialog.vue`
**Example Hidden:**
**Example Shown:**

Added component HiddenInput.vue

---

src/pages/Setup.vue

As mentioned in this [Card-68163579](https://github.com/louislam/uptime-kuma/projects/1#card-68163579) i added a auto login when the setup is done.
I could build in more error handling like in the original login component, but i decided for a push to `/` in either way. So if there is something wrong with it they'll see it in the normal login window.

Auto login after setup

---

src/pages/Settings.vue

1. Easy to edit
2. Easier to see differences between two export files (for example, just copy and paste here: https://www.diffchecker.com/diff)
3. No need to use external tools for formatting like https://jsonformatter.curiousconcept.com/

Format JSON file before download

---

src/pages/DashboardHome.vue

Previously the main events table would overflow on mobile. This simply fix the width.
| before | after |
| ------ | ----- |
|![image](https://user-images.githubusercontent.com/3271800/132945650-ea0a26d4-7b4d-492a-bfde-d4a524d20c7e.png)|![image](https://user-images.githubusercontent.com/3271800/132945515-ff383584-7f57-4106-8356-8ca4e25767fc.png)|

Fix: Fix events table width on mobile

---

server/notification-providers/discord.js
src/components/NotificationDialog.vue

This pull request add a new form element to the notification setup for discord.
You can enter a prefixMessage and it will be added as content message before the embed.
This is useful when you want to notify certain usergroups about the event.

add possibility to have a prefixMessage in discord notification before the embed

---

src/components/notifications/SMTP.vue

Password was set as "required". Changed to false to allow SMTP that doesn't require authentication.

Allow SMTP that doesnt require authentication.

---

db/patch10.sql
server/database.js
server/model/monitor.js
server/model/tag.js
server/server.js
src/components/MonitorList.vue
src/components/Tag.vue
src/components/TagsManager.vue
src/icon.js
src/mixins/socket.js
src/pages/Details.vue
src/pages/EditMonitor.vue

In the create / edit monitor page, the user can add new or select existing tags to apply to the current monitor. Any changes is stored as draft data in the `tagsManager` component, and will only be committed when the user click `Save` in the parent component. This made the code a bit more complicated, but I think the results are worth it.
Since the `Add tag` -> `Add monitor_tag` operation is order dependent, I wrapped the `socket.io` call in a Promise to be able to `await` it. I find this pattern way more usable then the default simple callback.
With a simple UX being top priority, I think there should be no need for a separate UI for managing tags. Instead, every time a `deleteMonitorTag` is triggered, it will remove any `tags` which is unused. So there is currently no way to change the …

Monitor: Tags with metadata

---

.dockerignore

* Add the following directories to .dockerignore: `test` and `kubernetes`.

Add missing entries to dockerignore

---

dockerfile
dockerfile-alpine
extra/entrypoint.sh

Start Docker container process with non-root user (**default** `1000:1000`). The user and group can be set during container startup with environment variables `PUID` for user and `PGID` for group. E.g. if you wish to run it with user **uid 2400** and **gid 3500** just run:
```bash
docker run -d --restart=always -p 3001:3001 -e PUID=2400 -e PGID=3500 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1
```
or set environment in compose file (for docker-compose or stack):
```yaml
version: '3.3'
services:
uptime-kuma:
image: louislam/uptime-kuma
container_name: uptime-kuma
environment:
PUID: "2400"
PGID: "3500"
volumes:
- ./uptime-kuma:/app/data
ports:
- 3001:3001
```
It does not require any user maintenance: Ownership of already existing files is modified (if necessary) during …

Docker entrypoint to run the application as non-root user

---

src/languages/nl-NL.js

removed some zero width spaces from the Dutch translations

fix(nl-NL): remove ZWSP from translation

---

dockerfile
dockerfile-alpine

* Small fix to add dumb-init. The main reason is to avoid zombie processes, and to properly pass signals to node.
Based on the changes from #416

Add dumb-init to avoid zombie processes

---

src/router.js

Reduce bundle size such that rollup no longer complains.

Build: Reduce client bundle size with more async components

---

server/prometheus.js
server/util-server.js
src/components/CertificateInfo.vue
src/components/CertificateInfoRow.vue
src/icon.js
src/mixins/socket.js
src/pages/Details.vue

In response to #514, improve the certificate info display such that the full chain is shown. Hopefully can help with debugging similar situations in the future.
Unfortunately the Certificate Icon is a premium icon in Font Awesome.
|light|dark|
|----|----|
|![image](https://user-images.githubusercontent.com/3271800/135607934-cf6863e0-a653-4bcf-8e40-3ca762124d97.png)|![image](https://user-images.githubusercontent.com/3271800/135608017-788494fe-66ad-46bf-a37a-532ca47ae611.png)|

Feat: Improve Certificate Info Display

---

src/components/Uptime.vue

Show tooltip when hovering the uptime percentage pill to indicate the time range of this uptime. Users should be able to find out if this is a 24h or 30d or other uptime metric.
- User Interface

24h tooltip on status page

---

CONTRIBUTING.md
config/jest-debug-env.js
config/jest-puppeteer.config.js
config/jest.config.js
package.json
server/database.js
server/server.js
src/assets/vars.scss
src/components/MonitorList.vue
src/components/settings/About.vue
src/components/settings/Appearance.vue
src/components/settings/Backup.vue
src/components/settings/General.vue
src/components/settings/MonitorHistory.vue
src/components/settings/Notifications.vue
src/components/settings/Security.vue
src/languages/README.md
src/languages/en.js
src/layouts/Layout.vue
src/pages/EditMonitor.vue
src/pages/Settings.vue
src/router.js
test/e2e.spec.js

As mentioned, the settings page is rapidly getting cluttered with different sections. The `Save` button is also in an awkward place as only some settings needs to be manually saved. I think a better design would be to have sections on the left side, and the main pane shows settings of this section only. The "Save" button can then appear only if that page needs to be saved.

UI: Redesign/organize settings page

---

src/pages/StatusPage.vue

When having lots of monitors and groups (hence having to scroll down to see the bottom of the list), adding a new group to the status page is a frustrating experience : 
- when the user clicks the `+ Add Group`  button, nothing moves on the visible part of the screen (the new entry is added at the bottom)
- the user has to scroll all the way down to find the new group entry
And when adding multiple groups, the user experiences repeatedly having to scroll up and down
Instead of adding the new group entry at the bottom of the page, add the new group entry at the top
- User Interface

🚸 Status page - add group action adds the new group at the top

---

src/components/settings/Appearance.vue
src/i18n.js
src/languages/README.md
src/main.js
src/mixins/lang.js
src/pages/Settings.vue

Load the language files on demand, rather than loaded all language files at startup.
No significant improvement. The page load speed should be faster theoretically, as the compiled index js file is smaller now.  
- Core

[wip] Lazy load language files

---

server/notification-providers/serwersms.js
server/notification.js
src/components/notifications/SerwerSMS.vue
src/components/notifications/index.js
src/languages/en.js
src/languages/pl.js

This PR adds support for SerwerSMS.pl as a notification provider via the HTTPS API v2: https://dev.serwersms.pl/https-api-v2/wysylanie-wiadomosci-sms-o-jednakowej-tresci

Add SerwerSMS.pl notification provider

---

ansible/playbook.yml

this is required because of configuration files should be present first.

fix: nginx role should run before uptime-kuma role

---

server/notification-providers/google-chat.js
src/components/notifications/index.js
src/languages/de-DE.js
src/languages/en.js

Fixes #1126 
In https://github.com/louislam/uptime-kuma/commit/f6fc3737fcb7d27582bd0dde6732157efc43138f#diff-4635d2896a4302c16ae5deb9f7075a0183ba388f249f1850a86fccb0efd66e6fR61 the name of the type for Google Chat was changed which caused a type mismatch stored in the notification provider.
This PR moves the translation to the translation files and fixes the type mismatch.

Fix Google Chat notification type mismatch

---

server/notification-providers/google-chat.js

when testing a Google Chat notification
see https://github.com/louislam/uptime-kuma/issues/1126#issuecomment-1006343423
Fixes #1126

fix `TypeError: Cannot read property 'id' of null`

---

server/ping-lite.js
server/util-server.js

When running on OpenBSD, there is an error : "Could not detect your ping binary."
The code already supports FreeBSD. And all the BSDs share the same ping path. So we can follow the same codepath. We just need to compare against "*bsd" and not the full OS name.

ping path is common to all BSDs

---

ansible/roles/uptime-kuma/tasks/main.yml

this will fix the problem when you change nginx configuration and containers are not reloaded

always recreate uptime kuma containers

---

server/prometheus.js

This fix address the issue described here: https://github.com/louislam/uptime-kuma/issues/1024
I can see this error in my logs from uptime-kuma every minute:
TypeError: Cannot read property 'daysRemaining' of null
at Prometheus.update (/app/server/prometheus.js:63:91)
at beat (/app/server/model/monitor.js:396:24)
at async Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:419:17)
FYI I'm not using Prometheus, just the base docker image with just a few http monitors configured, no special settings or anything
Fixes #1024

Fix for issue in logs

---

src/components/Login.vue

It would be nice to update the TOTP Token field's id to something like `otp, totp, 2fa, code, two-factor, challenge, token, mfa`  etc to support password manager filling, such as with 1Password's built in TOTP authenticators.
Some context from a similar issue:
https://1password.community/discussion/comment/544305/#Comment_544305
- Other
uptime-kuma
working example 1
working example 2 - bestbuy.com

Rename 2FA/TOTP field ID for password manager filling compatibility

---

src/components/settings/Security.vue

Slight rewording of the English translation message for the disable authentication warning.

Fix minor typos on disable auth warning

---

server/notification-providers/mattermost.js

The Mattermost integration currently has a small problem, which is if the name of the channel include Upper Case letters like `Uptime-Alerts` the backend will trigger a "Couldn't find the channel" error. This happens because the Mattermost expects the channel name in url in Lower Case as `uptime-alerts`.
People who use lower case letters for channels will not face this issue, but people who use Upper Case in channel will get above error.
Fixes #(issue)
- https://github.com/louislam/uptime-kuma/issues/1173
- https://github.com/louislam/uptime-kuma/issues/1202
Error Trace from logs:
```
Error: Error: Error: Request failed with status code 404 {"id":"web.incoming_webhook.channel.app_error","message":"Couldn't find the …
```

Fix mattermost couldn't find channel issue

---

src/assets/app.scss

The border colour of the checkbox has been changed to make it more
visible to the user when the dark mode is in use.
Signed-off-by: Computroniks <mnickson@sidingsmedia.com>
Previously, the check button with the label `Remember me` on the login page was near invisible for users using the dark mode due to the default bootstrap border colour being used. This PR fixes that issue by changing the border colour to `$dark-border-color`.
Previous colour:
New colour:

Fixed dark mode checkbox

---

server/model/monitor.js
server/prometheus.js
server/server.js

Fixes #598
Did a basic check that deleting, stopping and editing a monitor removes it from the metrics page. 
Feels pretty weird having to work around the existing implementation, but I'm not familiar with it enough to restructure it.

Fix: Remove prometheus metrics on delete [Test needed]

---

db/patch-proxy.sql
package-lock.json
package.json
server/client.js
server/database.js
server/model/monitor.js
server/model/proxy.js
server/proxy.js
server/server.js
src/components/ProxyDialog.vue
src/components/settings/Proxies.vue
src/languages/en.js
src/mixins/socket.js
src/pages/EditMonitor.vue
src/pages/Settings.vue
src/router.js

Added new proxy feature based on http and https proxy agents. Proxy feature works like notifications, there is many proxy could be related one proxy entry.
Supported features
- Proxies can activate and disable in bulk
- Proxies auto enabled by default for new monitors
- Proxies could be applied in bulk to current monitors
- Both authenticated and anonymous proxies supported
- Export and import support for proxies
- HTTP, HTTPS, SOCKS, SOCKS v5 SOCKS v4 protocols are supported
**Reviews are welcome** 🤩 
Fixes #470 
- User Interface

Feature monitor the resource over proxy

---

docker/docker-compose.yml

Add automatic restart for docker-compose.yml. 
It's the equivalent of `docker run -d --restart=always` for classic docker user.

Add automatic restart for docker-compose.yml

---

src/components/settings/Security.vue
src/languages/en.js
src/layouts/Layout.vue
src/mixins/socket.js
src/pages/Settings.vue

As titled. The user dropdown does not update after disabling auth until refresh.

Fix: Handle disabled auth in user dropdown

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

This PR is related to #1499 
It adds JSDoc documentation as a requirement when adding new methods and functions to the codebase.
- Other

Added JSDoc requirement in contributing docs

---

README.md

I updated the notification count from Readme.md to 90+ because 70 was outdated.
Apprise has 63 notifications services and uptime kuma has 33 native ones, so in sum its 96 and I think "90+ notification services" just sounds better than 96 and 70+.
- Other

Update notification count

---

.github/workflows/auto-test.yml

Upgrade to Github Actions actions/checkout@v3
Release notes here: https://github.com/actions/checkout/releases
Main difference is that v3 uses Node 16 instead of Node 14

Upgrade to actions/checkout@v3

---

CONTRIBUTING.md
README.md
src/languages/ru-RU.js

Fixes some typos in files
- Other

Typos fixes

---

src/components/PingChart.vue

Chart stops updating after switching back to "Recent".
Apparently it's a string, not a number.

Fix: Fix chart error on switch back to recent

---

server/notification-providers/aliyun-sms.js

aliyun-sms.js: escape more characters than encodeURIComponent
see https://help.aliyun.com/document_detail/315526.html
If a monitor name contain character `!*'()`, the notification won't send because the signature not match. This PR fixes this issue.

Fix aliyun-sms "SignatureDoesNotMatch" Error

---

server/notification-providers/apprise.js
src/components/notifications/Apprise.vue

Currently it's impossible to send a notification from uptime-kuma to a Zulip stream via the apprise integration. This is because some apprise backends (including messaging a Zulip stream) fail if the notification title isn't included in the request:
```
> docker run --entrypoint=apprise --rm caronc/apprise -vv -b "body" "zulip://<bot>@<organization>/<token>/<stream>"
2022-05-02 15:19:04,118 - INFO - Notifying 1 service(s) asynchronously.
2022-05-02 15:19:04,416 - WARNING - Failed to send Zulip notification to <stream>: Bad Request - Unsupported Parameters., error=400.
```
If we add the argument `-t "title"` the notification is sent correctly:
```
> docker run --entrypoint=apprise --rm caronc/apprise -vv -b "body" "zulip://<bot>@<organization>/<token>/<stream>" -t "title"
2022-05-02 …
```

Fix apprise integration for Zulip Streams

---

config/vite.config.js
package-lock.json
package.json
server/server.js
src/router.js

Just noticed that the dist js files size is very large now. It need to download 1.3MB files before a new user can see your status page.
Two ideas:
1. Try to chunk the js files manually, exclude some unnecessary modules for status page.
2. If above idea 1 is not working, maybe try to move this part out of vite.js and implement it in the traditional way without SPA.

Status Page Loading Speed Optimization

---

server/model/status_page.js

Fixes error loading status page when status page description is null.

Fix: Fix error when status page desc. is null

---

SECURITY.md

This PR removes a leftover comment from the security template in the `SECURITY.md` file
- Wiki/Docs-Update

Remove template comment in SECURITY.md

---

src/assets/app.scss
src/components/settings/Notifications.vue
src/components/settings/Security.vue
src/pages/Settings.vue

Fixes missing default setting for certificate exp. notif. Also slightly improve UI design to better match the design in `Security.vue`.
Anecdote:
Looking around the code base, we are a bit inconsistent in applying default settings because of historic reasons. Some settings are applied when they are first used (keepDataPeriodDays, tlsExpiryNotifyDays), some are applied when the user saves the Settings page for the first time (searchEngineIndex, checkUpdate). In theory if the user never saves the Settings, those keys will not be present. Hence individual features also has to handle case where the settings key does not exist.

Fix: Fix missing certificate exp. notif. default

---

src/assets/app.scss
src/components/MonitorList.vue
src/pages/List.vue
src/router.js

Hopefully Fixes #1764
Is there a particular reason why `/list` is inside `DashboardHome`? It breaks the `active` class automatically assigned by `vue-router`, so I moved it out for now.
| before | after |
| ------ | ------ |
| ![image](https://user-images.githubusercontent.com/3271800/173607803-5b9ab4c0-a684-4268-9acd-8c1abda7ef85.png) | ![image](https://user-images.githubusercontent.com/3271800/173607870-065995b4-d405-496f-9f23-6a1a71425c9e.png) |

Fix: Fix monitor list layout on mobile

---

src/layouts/Layout.vue

Fixes #534
Before
After
Although not an issue for this specific PR which I edited entirely on GitHub codespaces, running the linting commands locally has no effect. I have prettier on my editor which changed the styling, and the linting commands would not work.

fix: hide mobile header when not logged in

---

server/database.js

Avoid error "SQLITE_BUSY: database is locked" by allowing SQLITE to wait up to 5 seconds to do a write
I noticed in the logs of my Uptime-kuma container this error occuring several times per day:
```
uptime-kuma    | Trace: [Error: insert into `heartbeat` (`duration`, `important`, `monitor_id`, `msg`, `ping`, `status`, `time`) values (20, false, 2, '200 - OK', 116, 1, '2022-07-31 03:14:03.651') - SQLITE_BUSY: database is locked] {
uptime-kuma    |   errno: 5,
uptime-kuma    |   code: 'SQLITE_BUSY'
uptime-kuma    | }
uptime-kuma    |     at consoleCall (<anonymous>)
uptime-kuma    |     at Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:563:25)
uptime-kuma    | 2022-07-31T03:14:05.557Z [MONITOR] ERROR: Please report to https://github.com/louislam/uptime-kuma/issues …
```

Avoid error "SQLITE_BUSY: database is locked"

---

src/components/PublicGroupList.vue
src/pages/Details.vue
src/pages/StatusPage.vue

Add phishing security to link in status page. The use of ```Target="_blank"``` in <a> tags in HTML can be used to perform phishing. To avoid it it is necessary to add the argument ```rel="noopener noreferrer"```. This ensures the origin of the link. This argument is automatically added on some browser, but not all!
Sources:
https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/
https://stackoverflow.com/questions/50709625/link-with-target-blank-and-rel-noopener-noreferrer-still-vulnerable
- Security Fix

Add phishing security to link in status page

---

src/components/Login.vue

This will change the page title to " - Login" when the login form is shown. This is to help password managers to identify when the login form is shown.
I tried a few different ways, but this seems to be the easiest and least intrusive way. We have now three locations where the page title is set:
1. In 'index.html' where it is a hard coded html-Tag. (maybe we want to change this in the future...)
2. In 'src/pages/StatusPage.vue' around line 499 where it gets set to the title of the statuspage. (the hard coded html-tag gets completely overwritten)
3. (new) In 'src/components/Login.vue' around Line 58 to 64 - where the String " - Login" gets appended (or removed) to the page title.
Fixes #(issue)
#1864 
(including JSDoc for …

change page title to " - Login" when on Login Form

---

server/notification-providers/octopush.js

The version number was passed as a string from the frontend but was checked against a number in the backend provider. This caused the if else if to fall through into an error. The literal it is now being compared has been changed to a string and the unknown version error is no longer encountered. Fixes #2144 
I did also note that the legacy octopush API always returns 200, not an error code on failiure, instead giving the error message as …

Fixed Octopush Notifier not working #2144

---

server/notification-providers/octopush.js

The octopush legacy API does not return a HTTP error code and instead always returns a HTTP 200. This means that no error it thrown even if something like the parameters are incorrect.
Instead the error code is given in the json response data. Therefore we must look at the response data and check for the presence of the "error_code" key in the response data.
I can't find any documentation for the legacy octopush …

Fixed octopush legacy doesn't return error code

---

server/notification-providers/freemobile.js
server/notification.js
src/components/notifications/FreeMobile.vue
src/components/notifications/index.js

The french ISP https://mobile.free.fr provides an API to send SMS over a web requests to your own phone number.
I just set up uptime-kuma on my server and realized that it could be nice if I could receive updates on my phone when a service stops.  …

Add free.fr SMS notification provider

---

server/server.js

The change of the slug for the default StatusPage entry would cause the application to hit a 404 status code upon loading the main page.
The server was not properly loading the default entry point upon slug changes (see issue for more information).
_Notes:_
1. I've also taken the time to remove the deprecated `setting` function for the `getSetting` suggested one.
2. I haven't completely removed `exports.entryPage` as I'm unsure on whether or not it would cause side-effects to other parts of …

Fixed entry route not redirecting correctly.

---

server/model/monitor.js
server/util-server.js
src/pages/EditMonitor.vue

This PR adds support for the port to be specified when using the radius monitor type. A check has been implemented to ensure that a null value is not passed to the radius check function as could occur with monitors that were created before this change was introduced. The default port of 1812 is displayed when the user selects the radius monitor in much the same way as the DNS port is handled. The port was not included in the hostname in the form hostname:port in order to avoid issues with IPv6 …

feat: Added #2182 Add support for custom radius ports

---

src/components/HiddenInput.vue
src/components/notifications/ClickSendSMS.vue
src/components/notifications/GoAlert.vue
src/components/notifications/Gotify.vue
src/components/notifications/Line.vue
src/components/notifications/Matrix.vue
src/components/notifications/Octopush.vue
src/components/notifications/PromoSMS.vue
src/components/notifications/PushDeer.vue
src/components/notifications/Pushbullet.vue
src/components/notifications/Pushover.vue
src/components/notifications/Pushy.vue
src/components/notifications/SMTP.vue
src/components/notifications/ServerChan.vue
src/components/notifications/SerwerSMS.vue
src/components/notifications/TechulusPush.vue
src/components/notifications/Telegram.vue
src/components/settings/General.vue
src/components/settings/ReverseProxy.vue

As Google Chrome is trying to drop all v2 extensions next year, it is good time to say goodbye, Chrome.
After switched everything to Firefox and went to Uptime Kuma frontend, I noticed a few things and hopefully try to improve this in this pr:
- Password wrongly autofilling into empty api token fields (<Hidden ... />)
- The performance is noticeably slower than Chrome 
Read more on how bad is manifest v3:
- https://adguard.com/en/blog/manifestv3-timeline.html
- https://github.com/gildas-lormeau/SingleFile-Lite

Firefox Better Support

---

src/languages/README.md

Without this, you can have wrong indentation from ESLint
Check my commit https://github.com/louislam/uptime-kuma/pull/2264/commits/179c0b58a4e962252cd40f5672818f4092ec8c45 - it was run without `npm install` command. I fixed it here: https://github.com/louislam/uptime-kuma/pull/2264/commits/41fb023957ea6b7a34a3e291952e8b7b023484ea
- Other

Add info about `npm install` to translators

---

server/model/status_page.js

The variable `description155` becomes `undefined` if the description is `undefined`. 
This will be interpreted as an string in line `58` and will be printed as `undefined` in applications which render this tag.
My solution would be to use an empty string if description is undefined. We can also completely remove the tags but I didn't want to break anything which relies on it.
Example in Signal:

Fix 'undefined' in link preview generation

---

server/proxy.js
src/components/ProxyDialog.vue

Add socks5h support as an extra option to not break previous socks5 implementation.
Allows to toggle between socks5 and socks5h explicit.
Fixes #2296
Please do not use any external image service. Instead, …

Add socks5h support

---

server/model/monitor.js
server/notification-providers/discord.js

This fixes an issue where Docker Container alerts didn't get sent to Discord of an invalid field in some cases (don't know if I should've opened an issue, sorry)
Basically, the error field could have a value of `undefined` which Discord didn't like. This PR changes the error field to `N/A` if it isn't defined.

Fix discord notification not sending when docker container goes down

---

src/components/Uptime.vue

Title on 30 days uptime status now says that it is for 24-hour time period
This PR makes title for Uptime component a computed value. For type === "720", which is used here 
https://github.com/louislam/uptime-kuma/blob/839183aa8542fe484ed5e697ebb479502469c33a/src/pages/Details.vue#L73 
it returns localized value for "30-day"
Default value is still "24-hour"
(including …

Simple fix for Uptime component

---

server/notification-providers/discord.js

When using discord notifications the "Service URL" field in the notification message is different depending on the status. When the monitor is up, instead of just showing the URL, the link text is "Visit Service". This change makes both embeds show the URL directly. Look at the screenshots for more info.
Fixes #(issue)
Current implementation:
My change:

Improve the URL field in Discord embeds

---

server/model/monitor.js
server/server.js
server/util-server.js

Bug fix: gRPC check throws errors when response data size > 50 chars

---

db/patch-user-username-case-insensitive.sql
server/auth.js
server/database.js

Allows users to add users with capital letters and then login with just lowercase letters.
We accidentally capitalized the first letter of our username so the other people using it frequently thinks they wrote the wrong password.
Fixes #(issue)
- Breaking change (fix or feature that would cause existing …

Auth: Case insensitive login check on username

---

src/languages/fr-FR.js

Set "Not available, please setup" translation more accurate, because it's in use in notifications and proxies page.
Fixes a translation issue in french (no issue existing).

Improve french translation

---

server/model/monitor.js

Fixes #2289
The container monitor does not throw error when container is not running, which causes retries to not work.

Fix: Fix incorrect handling for container down

---

src/pages/Details.vue

Removed excess padding on dropdown
Fixed #2419 
Before:
Now:
(Text to the side is a log message, not part of the change)

Fixed #2419 Styling of clear data dropdown

---

server/notification-providers/splunk.js
server/notification.js
src/components/notifications/Splunk.vue
src/components/notifications/index.js

This adds Splunk (Previously VictorOps) as a notification provider for uptime kuma.
We really like this project at my company but we use Splunk so I added it myself and have been using internally for a little while, wanted to make sure I contributed it back!
Setup:
Example of a triggered and auto-resolved alert(some fields redacted): 
Please do not use any …

Add Splunk Notification Provider

---

server/server.js
src/assets/localization.scss
src/components/DockerHostDialog.vue
src/components/Tag.vue
src/components/TagEditDialog.vue
src/components/TagsManager.vue
src/components/settings/Tags.vue
src/languages/en.js
src/pages/Settings.vue
src/router.js
src/util-frontend.js

- View tags and monitors belonging to that tag
- Edit tag name & color
- Delete a tag (option to delete monitors with that tag?)

Feat: Tags Manager

---

server/notification-providers/promosms.js
src/components/notifications/PromoSMS.vue
src/languages/en.js
src/languages/pl.js

Fixes #2544 
In notification settings, You can now enable long messages to be sent. It will cost extra (for additional SMS). 
It allows to sent messages up to 4 SMS instead of 1 (160 chars).
By default, this option is disabled. 

Fix: Allow long sms in PromoSMS

---

server/model/monitor.js

Not sure if this should help with #2630, but better unify the options I guess?

Fix: Use default timeout & CachebleDnsHttpsAgent for docker monitor

---

server/model/monitor.js

Fixes logging format in docker monitor. Previously it would show undefined since call format is incorrect.

Fix: Fix incorrect log call format in docker monitor

---

src/components/Uptime.vue

Commit message:
Fixes #2628
A sanity check is performed when calculating the uptime of a monitor on status page. If it is greater than 100%, we just show 100%. This hasn't been implemented on the dashboard at the request of @louislam due to concerns it would make debugging more difficult in future if changes were made to the uptime calculation.
(including JSDoc for …

Perform sanity check on uptime for status page

---

server/config.js
server/routers/api-router.js

Fix: Add support for pending & maintenance in badges

---

server/config.js
server/model/monitor.js
server/routers/api-router.js

Creates Parody Between Statistics Shown In The Dashboard and Available Badges.
Issues such as #2176 show there is a clear need for full feature and name parity between the dashboard and badge system for simplicity.
I have created a new set of badges under `/api/badge/:id/` to cover the parody.  I have also changed the default label for `/api/badge/:id/ping/:duration?` and `/api/badge/:id/uptime/:duration?` to reflect the new badges.
All badges have the same options as the previous badge system.
Note: All examples are from `https://google.com`.
Shows the status of the monitor. (Existing badge) `/api/badge/:id/status`
Shows the response (ping) of the monitor. `/api/badge/:id/response`
Shows the average response (ping) of the monitor. (Rename of existing badge) …

Feat: Expand and Simplify Badge Functionality

---

.github/workflows/auto-test.yml
.github/workflows/close-incorrect-issue.yml
.github/workflows/stale-bot.yml

Do not run auto-test for markdown-only commits. Update versions for close-incorrect-issue and stale-bot
- Other

Do not run auto-test for markdown-only commits. Update versions

---

server/util-server.js

If connection cannot be established, `connection.end()` will trigger error since it will try to send command to a closed socket.
```go
Trace: Error: Can't add new command when connection is in closed state
at Connection._addCommandClosedState (C:\Dev\uptime-kuma\node_modules\mysql2\lib\connection.js:148:17)
at Connection.end (C:\Dev\uptime-kuma\node_modules\mysql2\lib\connection.js:855:26)
at C:\Dev\uptime-kuma\server\util-server.js:327:32
at <anonymous>
at runMicrotasks (<anonymous>)
at …
```

Fix [MySQL monitor]: Fix error when connection failed

---

.dockerignore
.gitignore
docker/debian-base.dockerfile
extra/remove-2fa.js
extra/reset-password.js
package-lock.json
server/database.js
server/jobs/util-worker.js
server/server.js
server/setup-database.js
server/util-server.js
src/lang/en.json
src/mixins/socket.js
src/pages/Entry.vue
src/pages/SetupDatabase.vue
src/router.js
test/backend.spec.js

An express app that is used for preparing `db-config.json` before Uptime Kuma is actually started.

Database Setup Page

---

server/database.js

A check to ensure that the backup database exists before deleting the current database. This prevents the current database being deleted when attempting to restore from a backup if said backup doesn't actually exist. This fail state can occur when operating on systems with low disk space as seen in #2778 .
Fixes #2778

Bugfix: Added check to ensure backup exists when restoring

---

src/i18n.js

Added a language translations (Finnish)
- Other

Added Finnish language translation

---

server/model/monitor.js
server/server.js

in preperation for #2491,#680 and #898
- Preperation for #898 (#680).
- Exposing it with `getPrometheus` for #2491.
- Removed the call `server.monitorList[monitor.id]?.prometheus()?.remove();` as `editMonitor` always restarts the monitor and does the remove already in `monitor.stop`.
Thought I split #898 in some smaller changes to make it more simple to review.
- Other
(including JSDoc for …

remember prometheus instance and expose it

---

server/notification-providers/slack.js

Fixes #2706 by taking the existing message displayed using Block Kit and including it in the text to provide a more detailed Slack notification.

Adds name + status + message to Slack notification

---

server/routers/api-router.js

Fixes #2840. Cache was not updated on push beat, which led to incorrect uptime display.

Fix: Clear uptime cache on push beat

---

server/notification-providers/lunasea.js
src/components/notifications/LunaSea.vue

Add the ability to use User ID for LunaSea notifications (Keeps all existing functionality).

Add ability to use User ID for LunaSea notifications

---

src/components/notifications/SMTP.vue

#2941 mentations that `{{URL}}` has been removed as template of smtp custom subject in [Server Side](https://github.com/louislam/uptime-kuma/blob/61506b1af23061efe30c9d687f50d71f197de7e6/server/notification-providers/smtp.js) and still remaining in [Client Side](https://github.com/louislam/uptime-kuma/blob/61506b1af23061efe30c9d687f50d71f197de7e6/src/components/notifications/SMTP.vue#L99)
Simpily removed it from Client side.
Fixes #2941

remove redundant template in smtp custom subject

---

src/lang/en.json
src/pages/StatusPage.vue

Partially addresses #978. Refresh interval not configurable yet, but value is stored in vue.js data now instead of hard-coded.

Feat: Add status page countdown to refresh

---

server/notification-providers/twilio.js
server/notification.js
src/components/NotificationDialog.vue
src/components/notifications/Twilio.vue
src/components/notifications/index.js
src/lang/en.json

You can receive notifications in the form of SMS via Twilio. All you need for this is a Twilio account. (Account SID, Auth Token, Phone Number) You can create a new account here. https://www.twilio.com
Feature Request https://github.com/louislam/uptime-kuma/issues/2964 

Add Twilio Sms Notification Provider

---

server/proxy.js

Fixes #2981
According to https://github.com/TooTallNate/node-socks-proxy-agent/pull/70 `rejectUnauthorized` is handled as an extra parameter.
Untested.

Fix: Pass rejectUnauthorized to Socks Proxy

---

server/notification-providers/ntfy.js

Improve ntfy notifications.
- use tags `red_circle` for down and `green_circle` for up
- increase priority for down alert by 1 if not already max
- add monitor name and status to title
- use heartbeat msg as Message
- add monitor url as action
- Other (improve notification provider)

Improve ntfy notifications

---

src/pages/EditMonitor.vue

The gRPC url regex has never worked, since the backslash was not correctly escaped. Combined with #2867 I think there is no point keeping it there.

Fix: Remove invalid gRPC url regex

---

server/database.js

Fixes #1980. I mainly use this for making a clean database backup (only the .db file is needed). Might be helpful in case WAL is stuck not flushing somehow.
- Other

Chore: Flush WAL on shutdown

---

src/assets/multiselect.scss
src/components/Tag.vue
src/components/TagEditDialog.vue
src/pages/StatusPage.vue

Follow up on #2752, use the same design in the Edit Tag dialog.
- Fix incorrect text colors in dark theme
- Reduce margins to improve alignment
|Before|After|
|------|-----|
|![image](https://user-images.githubusercontent.com/3271800/229881815-92c79f8a-fee3-4e03-ac04-4286c5c1190f.png)|![image](https://user-images.githubusercontent.com/3271800/229881104-38832d22-e47b-4483-ab85-3acf30f33eb3.pn …

UI: Use vue-multiselect in Edit Tag & Styling Fixes

---

server/model/monitor.js

Add `.trim()` to remove excessive whitespace from response body in keyword notifications so the useful part of the body is visible.
Fixes #3053 
- [N/A] I have commented my code, particularly in hard-to-understand areas
- [N/A] My code needed automated testing. I have added them (this is optional task)
Examples:
Before: 
```
[example.com] [🔴 Down] 200 - OK, but …
```

Trim before truncating "keword not found" message

---

server/notification-providers/pushover.js
src/components/notifications/Pushover.vue
src/lang/de-CH.json
src/lang/de-DE.json
src/lang/en.json

Since pushover 4.0 the message api supports [setting a TTL](https://pushover.net/api#ttl). This PR adds this option to the frontend and backend.
Fixes #3144 

feat: Adds message ttl to pushover notification

---

src/components/APIKeyDialog.vue

The `modal-footer` was inside `model-body`, instead of in `modal-content`.
|before|after|
|------|-----|
|![Screenshot 2023-05-31 092607](https://github.com/louislam/uptime-kuma/assets/3271800/ab7c5195-4fda-4503-a3aa-5843759bf0b5)|![Screenshot 2023-05-31 092534](https://github.com/louislam/uptime-kuma/assets/3271800/f83b470e-f053-4396-9e54-704 …

Fix: Fix incorrect modal layout in generate api-key

---

server/prometheus.js

The prometheus monitor_status metric has actually 4 values. This can easily be verified by looking up the related source code or by using the metric in grafana an see values like 2 (which indicates timeout).
Fixes #(issue)

Fix: prometheus monitor_status metric has 4 values

---

src/assets/app.scss
src/lang/en.json
src/pages/EditMonitor.vue

- Add help message when no group monitor is available
- Improve legibility of disabled select in dark theme
|before|after|
|------|-----|
|![image](https://github.com/louislam/uptime-kuma/assets/3271800/3abb4e7f-2b79-4120-86e1-42fba7bc0f17)|![image](https://github.com/louislam/uptime-kuma/assets/3271800/0255b326-c8a5-4564-80ad-0d2ae5b3bdb2)|

UI: Improve no group monitor message

---

server/notification-providers/home-assistant.js

Strip trailing slashes to avoid 404 from Home Assistant's API endpoint.

Strip trailing slashes to avoid 404 from Home Assistant's API endpoint

---

server/model/monitor.js
server/server.js

Fixes #3262
2 Monitors in a group
Monitors unlinked after changing type

Added fix to remove children when type changed

---

server/database.js
server/server.js

- External mariaDB does not check for existence of the database before connecting.
- The User count check does not work on mariaDB.
Just from this little encounter, knex.js does not seem fun to use. Just getting the count requires such convoluted functions.

[2.0] Fix: Add external mariaDB setup

---

server/database.js
server/server.js

In SQLite, data is stored in pages. When data is deleted, the pages which store that data are marked as free in the "freelist", which can be reused when new data is added. This means that no actual delete happens on disk.
In the past, we found that the database size increased a lot in long term use, and deleting data doesn't free up disk space. `auto_vacuum = FULL` was added to solve this issue.
According to the SQLite [documentation](https://www.sqlite.org/pragma.html#pragma_auto_vacuum), when `auto_vacuum` is set to full, on every transaction freelist pages are moved to the end of the file and truncated. If you think about it, this is terrible for our use case, since all our heartbeat data is inserted interleaved:
```
Heartbeat table …
```

[Experiment] Use incremental vacuum to speed up delete?

---

server/server.js

chore: notification toggle missing when import from backup

---

server/model/monitor.js

This PR adds support for the docker health Status. I thought that would be nice to have. I did not find any similar PR or Issue. It was not that much to change. For a Preview see Screenshots with comments below. (It's my first PR ever, so please don't be hard with me)
unhealthy is currently marked as PENDING, but could also be marked as DOWN. I'm not sure what's the best in this case.
This is a Healthy Docker Container
And this is the Normal Status of a Docker container without a health status.

Added Docker Health Status Support

---

.github/workflows/auto-test.yml

Inspired by @Zaid-maker #3333, try to find out if the npm cache is necessary in the first place. As I can see downloading the npm cache to runners could be slow somtimes. I will compare the build time.

[Experiment] Remove npm cache from the auto test workflow

---

server/jobs.js
server/jobs/clear-old-data.js
server/jobs/incremental-vacuum.js

Follow up on #2800, After discussion in #3286, here are the optimizations implemented:
- Every 5 minutes, run `incremental_vacuum(200)` and `wal_checkpoint(PASSIVE)`
- Every night after clearing old data, run `optimize`
Number `200` is chosen arbitrarily after reading [this article](https://www.theunterminatedstring.com/sqlite-vacuuming/). 
Ideally, we need to merge this before `1.23`. Have not tested this in a heavily loaded server. More actual testing would be preferred.
- Other
(including …

Feat: Run incremental_vacuum and optimize

---

server/model/monitor.js
server/util-server.js

Fixes #3185. Untested. If the monitor timeout becomes configurable in the future this can be passed the same variable.
While searching for the documentation of `node-radius-client`, I found out the repository that npm pointed to has disappeared from public view (https://github.com/w3cj/node-radius-client). IMO this is a pretty bad situation as we will be unable to raise issues if any were found. But there seems to be no alternative to this package so I guess we will have to stick to the status …

Fix: Set radius connection timeout to monitor default

---

src/pages/StatusPage.vue

```
[Vue warn]: Invalid prop: type check failed for prop "value". Expected String with value "Wed, 28 Jun 2023 22:54:34 GMT", got Object
```
Apparently `DateTime.vue` is not suppose to take an object. Remove its use fixes this.

Chore: Fix incorrect data type for DateTime component

---

server/uptime-kuma-server.js
test/backend.spec.js

This PR fixes the handling of IPv6 addresses in `getClientIP`. Currently this method fails to handle IPv6 addresses correctly. E.g. my log shows:
```
2023-07-08T00:15:01+02:00 [RATE-LIMIT] INFO: remaining requests: 19
2023-07-08T00:15:01+02:00 [AUTH] INFO: Successfully logged in user admin. IP=ca44
2023-07-08T00:15:02+02:00 [SETTINGS] DEBUG: Get Setting: initServerTimezone: null
```
when I logged in from `xxxx:xxxx:xxxx:xxxx:59a9:4a64:bea4:ca44`.
This is fixed by not blindly removing anything …

Fix handling of IPv6 addresses in getClientIP

---

src/lang/en.json
src/pages/EditMonitor.vue

Fixes https://github.com/louislam/uptime-kuma/issues/3468#issuecomment-1647709110
- makes the placeholder translatable
- requires the query and connection string
- simplifying the code a bit (idk, why these templates were duplicated...)
- Other

Chore: make sql monitors eazier to use

---

server/model/monitor.js
server/util-server.js
test/test-radius.dockerfile

Fixes #3486
- Adds a dockerfile for setting up a test radius server
- Propagate the radius error, instead of setting the bean to down directly, to work with retries
While fixing this bug, I found 2 annoying issues with the `node-radius-client` library:
- The library has a built-in retry mechanism, and defaults to 3 retries. A bug in the library also prevents me from disabling this retry mechanism. This would interfere with our own retries and timings. For example, if you set our beat interval …

Fix: Incorrect radius error & retry handling

---

src/mixins/socket.js

`favico.js` has a queue limit of 100 ([source](https://github.com/ejci/favico.js/blob/6a3f430be559f93d96573e2a4a0116e154c11319/favico.js#L333)).  Too many monitors going down at the same time will cause error:
```
Uncaught (in promise) Error: Error setting badge. Message: Too many badges requests in queue.
_readyCb favico.js:337
badge favico.js:341
down socket.js:763
```
This attempts to add a simple debounce to the favicon update. …

Fix: Add debounce to favicon update

---

src/mixins/socket.js

Showing an up/down toast message depends on getting the monitor name from `monitorList`. Here is the race condition:
1. Initial page load
2. server sends a very long `monitorList`
3. server sends a up/down heartbeat 
4. client tries to show toast, but `monitorList` has not finished loading.
```
Uncaught (in promise) TypeError: this.monitorList[data.monitorID] is undefined
initSocketIO socket.js:189
emit index.mjs:136
emitEvent socket.js:498
```
Prevent toasts from showing if monitor name …

Fix: Prevent race condition in showing toast message

---

CONTRIBUTING.md

Well... it's just to fix a typo in a markdown file 😉

fix: typo in contributing guide

---

server/model/monitor.js
server/server.js
src/components/ActionSelect.vue
src/components/CreateGroupDialog.vue
src/pages/EditMonitor.vue

Resolves #3376
Based on feedback from #2692 and #3376, further improve the UX of creating groups:
- Add simple dialog to create group when in the EditMonitor page.
The "Group Empty" initial beat is a bit annoying, but don't see an easy way to fix it.

Feat: Create Group in EditMonitor page

---

server/docker.js
server/model/monitor.js

Fixes #2353 
Currently it's not possible to add a remote docker daemon that is [secured with TLS](https://docs.docker.com/engine/security/protect-access/#use-tls-https-to-protect-the-docker-daemon-socket) because in this case the client needs to include the client side TLS certificate, issued by the docker host's CA, in every request. 
This PR adds the ability to include client side certificate in HTTPS requests to docker hosts by looking for the certificate files at a specified location in the file system and including them in requests. Certificates for multiple docker hosts can be made available to Kuma as described below.
The base path where certificates are looked for can be set with the `DOCKER_TLS_DIR_PATH` environmental variable or defaults to `data/docker-tls/`. 
If a directory in …

FEAT: Allow client side TLS for Docker hosts

---

db/patch-add-gamedig-given-port.sql
server/database.js
server/model/monitor.js
server/server.js
src/lang/en.json
src/pages/EditMonitor.vue

Fixes #2887. Try to make this not confusing is really hard.

Feat: Add givenPortOnly to gamedig options

---

server/notification-providers/aliyun-sms.js

Throw error when sending Aliyun SMS failed, snapshot below.

Fix(notification-aliyun-sms): throw error when sending SMS failed

---

.github/workflows/auto-test.yml

setup-node 3.8.0 has been released, try to remove workaround.
https://github.com/actions/setup-node/releases/tag/v3.8.0
Closes https://github.com/actions/setup-node/issues/793

Fix armv7 workflow

---

server/notification-providers/opsgenie.js

Fixes #3613
Our frontend sets the values for `opsgenieRegion` to `en` and `us` respectively => checking for `EN`/`US` won't work.
This is the code checking the variable:
https://github.com/louislam/uptime-kuma/blob/9564550d5fd01daade5b9d0935ca2ac065ea1068/server/notification-providers/opsgenie.js#L22-L31
While this is the code setting the variable:
https://github.com/louislam/uptime-kuma/blob/8945316ce660ade855aa7da379a87187489a1662/src/components/notifications/Opsgenie.vue#L4-L11
Please …

bug:`opsgenieRegion` not being usable

---

server/docker.js

Fixes https://github.com/louislam/uptime-kuma/issues/3605
This seems to have broken due to https://github.com/louislam/uptime-kuma/pull/2852 introducing this line:
https://github.com/louislam/uptime-kuma/blob/9564550d5fd01daade5b9d0935ca2ac065ea1068/server/docker.js#L144
This is a problem because this is called here without the `baseURL` ⇒ `undefined`:
https://github.com/louislam/uptime-kuma/blob/9564550d5fd01daade5b9d0935ca2ac065ea1068/server/docker.js#L71-L84
Before:
After:
Please delete any …

bug(regression-1.23): fixed local docker not working anymore

---

CONTRIBUTING.md
README.md
SECURITY.md

- [✔ ] I have read and understand the pull request rules.
Corrects the spelling and grammar of the main readme file and other markdown files.
Cosmetic, spelling and grammar fixes of Markdown files.
- Other
- [✔] My code follows the style guidelines of this project
- [✔] I ran ESLint and other linters for modified files
- [✔] I have performed a self-review of my own code and tested it
- [✔] I have commented my code, particularly in …

Spelling & Grammar updates

---

server/notification-providers/discord.js

When sending Discord notification for a gamedig monitor, show hostname:port (in line with steam and another types) instead of "https://"
PS: I know documentation says to create a draft pr before making a change, but I couldn't open one without making an actual change (if someone has a solution for that I will be glad to learn)
(including JSDoc for methods) (documentation not needed for this …

Show hostname:port for gamedig monitor on Discord notification

---

server/server.js
server/socket-handlers/docker-socket-handler.js
server/socket-handlers/maintenance-socket-handler.js
server/socket-handlers/proxy-socket-handler.js
src/lang/en.json
src/lang/hr-HR.json
src/lang/zh-HK.json
src/mixins/socket.js

Fixes #3259
I thought about adding a serverside translation library (like `i18next`), but each library has subtly different ways of handling things like regional fallbacks, interpolation etc. It's just not worth introducing another library to handle this. Also, if there exist an API for the server, we would not expect the returned messages to be translated. Hence I think we should focus on internationalization being a frontend problem only. But on the other hand, we may not want the frontend …

Feat: Translate toast messages by adding msgi18n to callbacks

---

src/components/MonitorListFilter.vue

- Added a "No tags found." message to the tags filter drop down in `MonitorListFilter.vue`
I noticed it appears to do nothing if there are no tags used. I checked the other filters but they will never be empty, so this is only needed for tags.
- Small UX enhancement

UI/UX: Added no tags found message to tags filter when empty

---

.github/workflows/auto-test.yml

Not sure what happened, but vite build is not working in Node.js 20.6.0. Fix it by pinning to 20.5.x

Fix auto test

---

server/database.js

Fixes incorrect database type check in function `sqlHourOffset()`.

Fix: Incorrect database type check in sqlHourOffset

---

src/pages/EditMonitor.vue

When editing a `json-query` monitor some HTTP options like `maxredirects` are currently not configurable. If I've understood the code correctly, this small change should fix that.
Unfortunately, I don't currently have a suitable environment to test these changes locally (and would prefer not to test them in the docker container on our staging server unless necessary). But the changes are very minimal so figured it was worth opening a PR instead of an issue that would pretty much contain the same information, except these changes can be easily tested and perhaps even merged.
Edit: fixes #3666.

EditMonitor: add missing config UI for json-query

---

src/pages/SetupDatabase.vue

Various small styling improvements to the setup-database page.
- [x My code follows the style guidelines of this project
|before|after|
|-----|-----|
|![image](https://github.com/louislam/uptime-kuma/assets/3271800/b287a10d-5624-476e-9fff-337273e2aa3c)|![image](https://github.com/louislam/uptime-kuma/assets/3271800/8982b413-9eb7-449e-9eb9-199ce53f4e10)|
|![image](https://github.com/louislam/uptime-kuma/assets/3271800/cedc5715-4269-42e2-be63-01 …

Fix: SetupDatabase misc. styling fixes

---

server/model/monitor.js

Fixes #3058
Previously, we `await` on all the async operations in a beat before scheduling the next beat, which means that any blocking operation and timeout will count towards the interval of the next beat. This will drastically increase the duration for long timeouts, and lead to inconsistent beat intervals. 
A very simple fix is to schedule the next beat right at the start, so no other operations can affect the accuracy. This gets the beat interval accuracy down to 5-15ms on a `Ryzen 5 …

Fix: More accurate heartbeat Interval

---

server/util-server.js
src/pages/EditMonitor.vue

I have refactored kafka producer error handling, also fixed ssl checkbox problem in UI
Fixes #3760

🐛 fix: kafka producer bugs

---

server/server.js
server/socket-handlers/api-key-socket-handler.js
server/socket-handlers/docker-socket-handler.js
server/socket-handlers/general-socket-handler.js
server/socket-handlers/maintenance-socket-handler.js
server/socket-handlers/proxy-socket-handler.js
server/socket-handlers/status-page-socket-handler.js
src/lang/en.json

Follow up on #3263, add remaining untranslated strings in server responses.
I reviewed the code change, but did not manually test that every message displayed correctly.

Chore: Add remaining server translation keys

---

server/model/monitor.js

Fix wrong datatype stored for avgPing causing unit to not display.
|before|after|
|-----|-----|
|![image](https://github.com/louislam/uptime-kuma/assets/3271800/1c34b2b2-4cf4-4c59-bc16-7441a3d0c5ea)|![image](https://github.com/louislam/uptime-kuma/assets/3271800/06bb6a56-1bfb-4be6-9aa4-ed2f7c047439)|

Fix: Wrong datatype for avgPing

---

server/routers/api-router.js

Reverse proxy has no support for `/api/entry-page`.
before:
```
curl -H 'x-forwarded-host: status.xuexb.com' 127.0.0.1:9800/api/entry-page
{"type":"entryPage","entryPage":"dashboard"}
```
after:
```
curl -H 'x-forwarded-host: status.xuexb.com' 127.0.0.1:9800/api/entry-page
{"type":"statusPageMatchedDomain","statusPageSlug":"main"}
```

Fix: Update `x-forwarded-host` field when using reverse proxy

---

src/pages/StatusPage.vue

Fixes #3848.
Cannot reproduce the described bug since data should be preloaded, but maybe browser performance is a factor in this.

Fix: Disable status page saving before getData

---

.eslintrc.js
server/database.js
server/notification.js
server/server.js
server/setup-database.js
server/uptime-kuma-server.js
src/util.js
src/util.ts

Also the server will exit with exit code `1` instead of `0` if start failed.

Log color and simplify startup log for production

---

src/layouts/Layout.vue

Fixes the clear toasts button blocked by the save button bottom bar in `EditMonitor`. Also increased the shadow opacity on dark mode such that it should be a bit more visible.
|before|after|
|------|-----|
|![image](https://github.com/louislam/uptime-kuma/assets/3271800/de9a7569-f8c6-4a6f-85d5-4825e531044f)|![image](https://github.com/louislam/uptime-kuma/assets/3271800/734641b8-1ee6-4052-a45 …

Fix: Clear toasts button blocked by bottom bar

---

docker/debian-base.dockerfile

Originally want to update to Node.js 20, but build fail due to missing armv7 image.

Update docker image base from Node.js 16 to Node.js 18 for Uptime Kuma v1

---

server/model/monitor.js
server/util-server.js

Fixes #3323
Store the fingerprints of the known root certificates that are bundled with node.js. When checking certificates for expiry notification, stop when a known root certificate is encountered.
Note that this does not account for extra certificates imported by using `NODE_EXTRA_CA_CERTS`.

Fix: Stop notification check on root certs

---

server/monitor-types/real-browser-monitor-type.js

Adds MS Edge to the list of allowed browsers. Tested should be working.
- Other

Chore: Allow MS Edge for real-browser monitor

---

server/model/monitor.js
server/uptime-kuma-server.js

I was experiencing the same issue again
Fix #736 
Fix #2879
Fix #3946
I guess maybe the last heartbeat was never end. I suspected that it is due to very rarely issue of axios which do not respect the timeout config, since all reports were so far related to the HTTP monitor only.
But it is all my guess only. It is really hard to be reproduced. 
So, instead of fixing the actual issue, this pr try to detect monitors that in such state and restart them.

Restart running monitors if no heartbeat

---

server/model/monitor.js
server/util-server.js

According to [axios#5886](https://github.com/axios/axios/issues/5886) and [axios documentation](https://axios-http.com/docs/cancellation), the `timeout` property is unable to handle connection issues. We should add an AbortSignal such that even if the connection is stuck, the request will be cancelled on time.
This feature is only available for node.js v15+. Try catch is added which should leave old versions unaffected.
(including JSDoc for …

Fix: Add axios abort signal

---

server/model/monitor.js
src/components/ActionSelect.vue
src/components/DockerHostDialog.vue
src/lang/en.json
src/pages/EditMonitor.vue

Fixes #3861
- Use action select for the docker host option
- Check that docker host is selected before save, and prevent saving otherwise
- Verify that docker host config is loaded on server in heartbeat
- Add a few props for the select and button states in ActionSelect for config and convenience
- Also handles the case where the docker host was deleted while in the `EditMonitor` page. …

Fix: Use ActionSelect for Docker Host & validate input

---

src/pages/Entry.vue

Fixes #3988. I'm guessing on a new database the setting is unset.

Fix: entryPage setting can be null

---

db/patch-fix-kafka-producer-booleans.sql

🐛 fix: kafka producer booleans migration null values

---

server/model/monitor.js

Fix #4033 
Should be because of Node.js 18. Don't want to create breaking changes in 1.23.X.

Keep Node.js 16's TLS behavior

---

db/patch-fix-kafka-producer-booleans.sql

Fix #4039
I think there are still some issues of these UPDATE statements, unfortunately SQLite does not always show a meaningful error message which makes it hard to be debugged.
My new idea is just drop these UPDATE statements, as before the patch, it is not actually working, it should be fine to migrate without values. 
For future, I think I won't allow changing column's type anymore, it is not easy to migrate.

Fix kafka migration script

---

server/model/monitor.js

The default cancelled message is not very informative. Added a sensible message when the error name is `CancelledError`.

Fix: Improve error message on timeout

---

db/knex_migrations/2023-09-29-0000-heartbeat-retires.js
server/model/heartbeat.js
server/model/monitor.js
server/routers/api-router.js

Fixes #4085
Fixes #3787
Fixes #3208
Fixes #1863
Make retries persist across restarts by storing the running value in the database, and handle them correctly for push monitors.
- Add column `retries` to the heartbeat table.
- Record retries in the push route and and heartbeat interval. Value continues to increment until another UP beat is received.
- Factor out the status transitions to function `determineStatus()`.
- Add code to handle notification resend and setting `downCount` to the push …

Feat: Retries persistence

---

package-lock.json
package.json
server/monitor-types/tailscale-ping.js
server/notification-providers/apprise.js
server/server.js
server/uptime-kuma-server.js

Fixed Tailscale monitor could possibly hang the whole Uptime Kuma application.
For future me, `execSync/spawnSync` should never be used. They could block the whole main even loop if the command is slow.

Change execSync/spawnSync to async

---

server/database.js

Fixes #3723
When datetime is returned from mariadb, the database driver automatically converts the result to the server's local timezone, whereas in the old sqlite code we assume the returned time is always in UTC. Setting `timezone` in the connection config does not seem to fix this. Following advice from another GitHub [post](https://github.com/knex/knex/issues/1461#issuecomment-317454301), override the `typeCast` config for the database driver seems to do the job.
- Bug fix (non-breaking …

Fix: Disable timezone conversion for mariadb

---

src/components/MonitorList.vue
src/components/settings/Notifications.vue
src/lang/en.json

Fixes #2150 which is stalled/stale/not going to go anywhere
Not a visual change, just adding an `aria-label` ^^

Add an `aria-label` to the monitor search box

---

extra/reset-password.js

This PR aims to provide a way to set the user password programatically which is useful when provisioning Uptime Kuma servers.
New feature
```
$ docker exec -t -i uptimekuma-prod /bin/bash -c 'npm run reset-password -- --new_password=secret'
> uptime-kuma@1.23.3 reset-password
> node extra/reset-password.js --new_password=secret
== Uptime Kuma Reset Password Tool ==
Connecting the database
2023-10-18T15:58:07+00:00 [DB] INFO: Data Dir: ./data/
Found user: admin
Using password from argument
Password reset successfully.
2023-10-18T15:58:07+00:00 [DB] INFO: Closing the database
2023-10-18T15:58:09+00:00 [DB] INFO: SQLite closed
Finished.
```

Adding a way to reset the admin password via CLI without any user interaction

---

src/util.js
src/util.ts

- The logging function is used in both frontend and backend, but Firefox does not support console coloring. Disable console colors when running in browser.
- Add missing JSDoc lines to silence warnings in `util.ts`.
- Other

Chore: Disable console colors in browser & add JSDoc

---

src/components/MaintenanceTime.vue

Fixes #4066
Correct Maintenance Start/End Time Input to Consider Daylight Saving Time (DST)
Timezone bug fix

Fix: Correct Maintenance Start/End Time Input to Use Explicitly Specified Timezone

---

extra/reset-password.js
server/server.js
server/uptime-kuma-server.js
src/mixins/socket.js

The current 1.23.9 fix isn't smooth for many reverse proxy users, leading people to add `bypass` to skip the checking, which is a bad idea.
~My new idea:~
My new new idea:

Smoothing the update for origin check

---

server/uptime-kuma-server.js

Variable `origin` needs to be defined outside of try...catch such that it can be displayed on error

Fix: `origin` undefined on error handling

---

server/model/user.js
server/server.js
src/components/settings/Security.vue

Currently, changing password would disconnect all websocket clients except the one that initiated the password change. However, this remaining client is now running on an invalid token even though it is still connected. Normal operations will still work since the `checkLogin()` function only verifies that the user has previously successfully logged in, but the user will be prompted to login again on browser refresh. I think this is not an intuitive UX, and we should either
- refresh the current …

Feat: Refresh login token for the client initiating password change

---

src/pages/Details.vue

Changed the color of the delete button in dashboard from red to grey as per the requirement. Just replaced class name from 'btn-danger' to 'btn-secondary' to achieve the changes.
@louislam 

Changed the color of delete button in dashboard from red to grey

---

db/knex_migrations/2023-12-21-0000-stat-ping-min-max.js
db/knex_migrations/2023-12-22-0000-hourly-uptime.js
server/uptime-calculator.js
test/backend-test/test-uptime-calculator.js

Decided to break out database and `UptimeCalculator` changes from #4264.
- Add `stat_hourly` table
- Add `ping_min` and `ping_max` columns to the stat tables
- Update `UptimeCalculator` to store these values
- Fix small typo in the original `update()` function `if (dailyData.up === 1) {`
- Breaking change (a fix or feature that would cause existing functionality to not work as …

Feat: Add `stat_hourly` & min. max. ping

---

server/model/monitor.js

Fix basic authorization for servers with empty password or empty user.

Fix `encodeBase64` for empty password or user in HTTP Basic Authentication

---

README.md

From: Linode (Tokyo, Japan / 2 Cores / 4GB RAM / $24 per month)
To: OVH (Frankfurt, Germany / 4 Cores / 4GB RAM / $11 per month)
Linode increased the price this year, which makes it a bit expensive. 
And the old server is CentOS 7, which will reach EOL soon. It is also a chance to switch to a up-to-date OS (Debian Bookworm)
Also it seems that putting the server in EU is a better choice of location.
Checklist:

Moving the server

---

server/notification-providers/dingding.js

See <https://github.com/louislam/uptime-kuma/pull/3573#issuecomment-1678029861>
https://github.com/louislam/uptime-kuma/pull/3598#issuecomment-1899523530

fix(notification-dingding): throw error when failed

---

server/monitor-types/real-browser-monitor-type.js

Maybe Fixes #4373, but haven't tried to reproduce it.

Fix: Make sure browser is connected before returning

---

server/monitor-types/real-browser-monitor-type.js

After adding type definition in #4417, I found that `browser` should be of type `Browser`, but `getRemoteBrowser()` is trying to assign `Promise<Browser>` to it.

Fix: missing await in `getRemoteBrowser()`

---

server/model/monitor.js

Fix: [JSON-Query] Prevent parsing string-only JSON

---

src/assets/vars.scss
src/components/HeartbeatBar.vue
src/pages/Details.vue
src/pages/Settings.vue

Feat: Show monitor ID in Details

---

package-lock.json
package.json

Surprisingly, axios 0.x is still being maintained.
Read more: https://github.com/axios/axios/releases/tag/v0.28.0

Update axios from 0.27.x to 0.28.x

---

server/routers/status-page-router.js

Fixes #4535
`StatusPageData` should always return something, so there is no need to check for its existence. sending HTTP Error response was however missing if the status page itself is not found.

Fix: Incorrect handling of status page not found

---

server/model/monitor.js
src/pages/Details.vue
src/pages/EditMonitor.vue

On the details view, the group text above the monitor name is generated by checking for slashes in `monitor.pathName`. This causes issues when the monitor name contains a slash. E.g. for the name `GitHub (/louislam)` the group `GitHub (` is detected.
What changed:
* a new property `path` on `Monitor` that stores the path as an array
* `pathName` is derived from `path` to not double the db requests
- Bug fix (non-breaking change which fixes an …

Fix: handle monitor names with slashes

---

server/notification-providers/ntfy.js

Fixes #3274
In ntfy v2.8 attempting to send a notification with an action that's missing a URL results in failure.
This bugfix was tested and is working with ntfy v2.8.

[Ntfy] Only include action link if monitor url is defined #3274

---

extra/reset-password.js

Upon detailed review of the issue, the only thing needed was to add a try catch block.
Code was already testing for db file existance 
Fixes #4518
no addition or deletion
just moved 2 lines in a try catch block 
Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded …

Test for db file existance instead of creating a new one in `password-restet.js`

---

server/monitor-types/mqtt.js

…ker to identify where the connections are coming from
I'm monitoring my MQTT broker for connections and found plenty that look like `mqttjs_466d1625`, so I wondered where they come from.
finally I found them to come from Uptime Kuma.
to make it easier to understand, I propose to set the MQTT `clientID` to include the term `uptime-kuma` to make it easy to identify.
the random part generation of the `clientID` follow the default format used by the `mqtt` lib, and I'm only setting a different …

Set `mqtt`-`clientId` to `uptime-kuma_..` instead of `mqttjs_..`

---

.github/workflows/auto-test.yml

~Adds a `--force` flag which fixes CI failing [source](https://stackoverflow.com/questions/39293636/npm-err-error-eperm-operation-not-permitted-rename)~
Seems like there is node-gyp issue due to drop of support of Node 14 which is preventing the CI to install global NPM version, ~removing the `npm i -g npm@9` fix the ci and seems OK~ Bumping to Node 16 fixes the issue
Tested the same method on my Repo CI it seems to run OK not the issue with NPM or Actions, i cannot figure out the issue.
Please …

fix(ci): Fix for the Actions failing on Windows Runner

---

db/knex_init_db.js
db/old_migrations/patch-monitor-tls-info-add-fk.sql
server/database.js

The `monitor-tls-info` table has missing foreign key referencing the `monitor table`. This leads to orphan tls-info entries when monitors are deleted, which may take up disk space. Adding back the foreign key by modifying the table schema fixes this.
This fix is for `2.0`. I think existing mariadb databases will not be affected. …

Fix: Add missing FK for monitor-tls-info table

---

db/patch-monitor-tls-info-add-fk.sql
server/database.js

The `monitor-tls-info` table has missing foreign key referencing the `monitor` table. This leads to orphan tls-info entries when monitors are deleted, which may take up disk space. Adding back the foreign key by modifying the table schema fixes this.
This fix is for `1.23.X` only.

Fix: Add missing FK for monitor-tls-info table [1.23.X]

---

server/notification-providers/slack.js

Fixes #3351: adds the monitor url as a button to the slack message. Also, restructured the code which adds the "Visit Uptime Kuma" button to be more readable and modular.
|Before| After|
|---|---|
|![image](https://github.com/louislam/uptime-kuma/assets/35113929/3f5fd021-ee7f-47f5-818b-71d834203493)|![image](https://github.com/louislam/uptime-kuma/assets/35113929/906eb7dc-def3-4ce5-a429-c87cb94ab7f8)|

[Slack] restructure alert actions, add 'visit site' button

---

package-lock.json
package.json

`11 vulnerabilities (1 low, 4 moderate, 5 high, 1 critical)`
EDIT:
`13 vulnerabilities (1 low, 6 moderate, 5 high, 1 critical)`
instead of
`14 vulnerabilities (1 low, 7 moderate, 5 high, 1 critical)`
Replaces PR https://github.com/louislam/uptime-kuma/pull/4647
Other vulnerabilities (and critical 9.8 CVSS https://github.com/advisories/GHSA-fqg8-vfv7-8fj8) could be fixed by simply deleting `package-lock.json` and doing `npm update`, but this is too much for PR. This was done by @louislam many times in the past...
Vite should be updated to `4.5.3` to fix `fs.deny` high vulnerability (7.5/10 CVSS score) (currently we are using `4.4.12` in 1.23.X branch).

fix: Update `axios`, `@actions/github` and `dompurify`  [1.23.X]

---

package-lock.json
package.json

Changelog: https://github.com/nodemailer/nodemailer/blob/master/CHANGELOG.md
https://github.com/advisories/GHSA-9h6g-pr28-7cqp
Fix 1 moderate vulnerability.

fix: Update nodemailer to fix GHSA-9h6g-pr28-7cqp [1.23.X]

---

server/model/monitor.js
server/util-server.js

This is a `1.23.X` version of #4281 with the minor new feature removed.

Feat: Use keylog event to obtain TLS certificate for better reliability [1.23.X]

---

CONTRIBUTING.md

Previously, I was using buildkit (qemu) to build arm64/armv7 docker image.
However, for some reason, it is no longer working for arm64. It is extremely slow and `npm ci --omit=dev` always failed with `npm ERR! errno ECONNRESET` error. Tested on different PCs and different networks. Maybe our `package-lock.json` is getting big now.
To overcome the issue, now I set up a special Docker builder which will pass the arm64 build job to my real arm64 machine.

Update CONTRIBUTING.md for how to set up a Docker builder

---

src/i18n.js
test/cypress/unit/i18n.spec.js

Resolves #4691
Resolves #4690
Resolves #4697
There were these minor bugs in the new language selection mechanism introduced in `1.23.12`:
- we only fall back to the generic locale (for `en-US` this would be `en`) for the first entry of the languages
- We never match `en` if other (less prefered) alternatives exist in the users preferences, as this is only in the messages and not in the `languageList`.
- We assumed that the generic locales are only 2 characters, not 3
Our testcases missed this …

fix: Localisation-matching algorithm missing some edgecase

---

server/server.js
src/mixins/socket.js

Hi @louislam, 
I'm the author of [AutoKuma](https://github.com/BigBoot/AutoKuma) (which is my main reason for this request) and  I'd like to suggest adding new SocketIO event when the server is expecting login credentials from the client. 
As it currently stands there is no way detect this besides just waiting for some predetermined time for an autoLogin event and otherwise assume credentials are required. 
I've noticed the WebUI also has this problem resulting in the Login UI poppung up for a …

Add `loginRequired` SocketIO event

---

server/model/monitor.js
server/prometheus.js

Fixes #4693
Fixes #4698
Also handles the issue in #3551 correctly
I think I found a way to listen for the `secureConnect` event, which eliminates the messy 2-step process of the previous fix. I also restored the old method of checking for the `tlsSocket` after the response is received, since the `proxy-agent` does not seem to work with the `keylog` event, but we can still obtain the TLS information through the socket.
Feel free to test.

Fix: Getting TLS certificate through proxy & prometheus update

---

src/components/settings/APIKeys.vue
src/lang/en.json

Fixes #4628
Show API Keys disabled message when Auth is disabled.
Small formatting change to existing code.

Fix: Show API Keys disabled msg. when disabled Auth

---

server/socket-handlers/status-page-socket-handler.js

Backport of https://github.com/louislam/uptime-kuma/pull/4750
Fixes #4749

chore: fixed a typo for internal, unused part of the file upload icon for status page

---

server/database.js

Knex sometimes throws `Error: read ECONNRESET`. Trying to improve this.
Reference:
https://github.com/knex/knex/issues/3447#issuecomment-1320931175

Improve MariaDB's connection

---

server/server.js
server/socket-handlers/chart-socket-handler.js
server/uptime-calculator.js
src/components/PingChart.vue
src/mixins/datetime.js
src/mixins/socket.js

Depends on #4267
Depends on #4406
Resolves https://github.com/louislam/uptime-kuma/issues/2251 as the jitter is now "printed"
Update PingChart to use data from the new `UptimeCalculator`. 
- Use 3 line charts to show the min, max and avg ping together for better visualization
- Avoid modifying `heartbeatList`, and instead store the received data in a separate data structure.
- With this method, there seems to be no easy way to show the maintenance period. How should we handle this? Adding …

Feat: Use `UptimeCalculator` for PingChart

---

.github/workflows/conflict_labeler.yml

Before merging the PR you have to manually add the label `merge conflict` 
Put a label `merge conflict` on PR with merge conflict and comment also to say to the maintainer that PR as merge conflict.
Would be simpler to review PR and also gain time cause when merge conflict is detected the maintainer can solve it so you don't have to say to him manually to solve the merge conflict.

feat: Add merge conflict labeler workflow

---

package-lock.json
package.json
server/database.js

Back in the day, the official one was not providing prebuilt for arm systems, that was why I forked it.
The official one does not support CentOS 7 anymore, but CentOS 7 is reaching EOL next month, so I don't care it anymore.

Switch back to `TryGhost/node-sqlite3` from `louislam/node-sqlite3`

---

src/lang/en.json
src/pages/StatusPage.vue

Translation `unpin` incident -> `delete` incident

---

server/notification-providers/feishu.js

Fixes #(issue)
| Event | Before | After |
|-------|-------|------|
| `UP` | ![image](https://github.com/louislam/uptime-kuma/assets/1142269/0f8ed824-b9be-4472-8d97-89d6a6def6e8) | ![image](https://github.com/louislam/uptime-kuma/assets/1142269/9da3af6c-63ee-4331-8b84-38360deb9036) |
| …

feat: update feishu notification template

---

.github/workflows/auto-test.yml

Prevent running Self-hosted ARM runner to run on forks as they keeps waiting for a runner to pick-up the job and eventually fails this will prevent from running in forks.
- Other

fix(ci): Prevent ARM runner from running in Forks

---

server/model/monitor.js

Fixes #4025 
@louislam @CommanderStorm 
Tagging you both as per [Contibution Guidelines](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#recommended-pull-request-guideline)
- Waiting for discussion
- All details about the change …

Fix: Use `retryInterval` when a monitor is `DOWN`

---

server/monitor-types/dns.js
server/monitor-types/mongodb.js
server/monitor-types/monitor-type.js
server/monitor-types/mqtt.js
server/monitor-types/real-browser-monitor-type.js
server/monitor-types/tailscale-ping.js

During https://github.com/louislam/uptime-kuma/pull/4806 I noticed that there has been some dirift in how we document `MonitoringType`s.
This PR removes the drift
- Other

removed some monitor drift in terms of code comments

---

server/notification-providers/discord.js
server/notification-providers/notification-provider.js
server/notification-providers/sevenio.js
server/notification-providers/smtp.js
server/notification-providers/squadcast.js
server/notification-providers/teams.js
server/notification-providers/zoho-cliq.js

- show PORT (cloned switchcase from discord,squadcast,servenio)
- show monitorName in the first row to get on point also from messagge preview notification
- avoid duplication of monitorName and monitorName in the message content
| …

improved zoho-cliq message format

---

server/notification-providers/threema.js
server/notification.js
src/components/NotificationDialog.vue
src/components/notifications/Threema.vue
src/components/notifications/index.js
src/lang/en.json

Adds a new notification provider for [Threema Gateway](https://threema.ch/en/gateway)

New notification provider: Threema Gateway

---

server/model/monitor.js

Reverts louislam/uptime-kuma#4476
Some of my monitors are going crazy after this pull request. 
I think they are old monitors, the `retry_interval` values in the db are `0`.

Revert "Fix: Use `retryInterval` when a monitor is `DOWN`"

---

package-lock.json
package.json
server/database.js

Even though we don't need to support CentOS 7 anymore, I completely forgot the official one doesn't provide armv7 prebuilt, that means I have to continue to maintain my fork.
Revert #4773

Revert "Switch back to `TryGhost/node-sqlite3` from `louislam/node-sqlite3`"

---

src/util.js
src/util.ts
tsconfig.json

I am not sure why it is suddenly not working on frontend.
According to https://day.js.org/docs/en/installation/typescript, adding `esModuleInterop` should fix the issue.

Fix dayjs issue on frontend

---

src/pages/Details.vue

Currently URL is not displayed for "real-browser" type monitor:
Fixes #(issue)
This change will make it appear.

Show URL for "real-browser" type monitor on details page

---

.github/workflows/stale-bot.yml

This pull request updates the Stale GitHub Action from version 8 to version 9. The primary reason for this update is that Node 16, which was used in version 8, is now outdated. The new version utilizes a more recent Node version, ensuring better security and compatibility.
No screenshots necessary for this update.

Update Stale GitHub Action from v8 to v9

---

server/notification-providers/onesender.js
server/notification.js
src/components/NotificationDialog.vue
src/components/notifications/Onesender.vue
src/components/notifications/index.js
src/lang/en.json

Fixes #(issue)
- Breaking change (a fix or feature that would cause existing functionality to not work as expected)
- Other
| Event | Before | After |
| ------ | ------|------|
| `UP` | - | ![image](https://github.com/user-attachments/assets/02c700cb-bf61-4da9-92dd-b75 …

Add OneSender Webhook notification

---

src/assets/app.scss

Fixes #4994
PrismJS text is not in sync with input text. Edited bold class to fix issue. PrismJS Reference: https://github.com/PrismJS/live/issues/15

fix: `!important` in the prim-css editor is rendered incorrectly

---

src/components/PublicGroupList.vue

Fixes #4365. 
Adjusted column values in PublicGroupList to extend status bars in small screens. 
I wasn't sure if the request was asking to extend for all or just small screens. Based on the screenshot, I assumed the latter.

Extend length of status bars in status page

---

src/pages/DashboardHome.vue

Fixes #3293 name column in the dashboard being squashed in some aspect ratios @louislam 

Fix: name column in the dashboad being squashed in some aspect ratios 

---

src/lang/en.json
src/mixins/socket.js

Add translation keys
Fixes #(issue)
- Other

Add translation keys

---

server/notification-providers/signl4.js
server/notification.js
src/components/NotificationDialog.vue
src/components/notifications/SIGNL4.vue
src/components/notifications/index.js
src/lang/en.json

New notification provider SIGNL4 added.
This PR adds SIGNL4 as a notification channel for Uptime Kuma.
| Event | Before | After |
| --- | ------- | -------- |
| `UP` |  -  |   ![monitor-down-alert-triggered](https://github.com/user-attachments/assets/606035d7-0181-447d-b0c5-d7dadbbf6061) |
| `UP` |  -  |   ![monitor-down-alert-triggered](https://github.com/user-attachments/assets/606035d7-0181-447d-b0c5-d7dadbbf6061) |
| `DOWN` | -  | …

New Notification Provider SIGNL4

---

server/server.js

⚠️ Please verify that this question has NOT been raised before.
🛡️ Security Policy
📝 Describe your problem
Hi,
While I was setting up the monitors, I saw `undefined` was written in info log. I checked the monitor object and found there's no id in that object which we are using while logging the info log resulting in undefined.
📝 Error Message(s) or Log
[MONITOR] INFO: Added Monitor: undefined User ID: 1
🐻 Uptime-Kuma Version
1.23.13
💻 Operating System and Arch
N/A
🌐 Browser
N/A
🖥️ Deployment Environment
x
✔️ Solution
Logging `monitor.name` instead of `monitor.id`
Screenshots

fix: undefined in log while creating a new monitor

---

package-lock.json
package.json
server/model/status_page.js
server/routers/status-page-router.js

Fixes #1673.
This PR adds RSS capabilities to status-pages without extra configuration.
It's implemented as a custom route: append `/rss` to any status URL to get the RSS feed.
I've checked out the discussions in #2129 and #1673.
This PR adds a new server-side dependency `feed`.
Right now, the RSS feed looks like this:
```bash
curl http://localhost:3001/status/abc/rss
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
<channel>
<title>uptime kuma rss feed</title> …
```

feat: implement very crude and bare-bones RSS feed

---

src/components/MonitorListItem.vue

Fixes bug where monitors in subgroups are not visible due to the `filterFunc` not being passed on recursively.
Before:
After:

Fix missing monitors in subgroups due to missing filterFunc

---

package-lock.json
package.json

Fixes #5141
cheerio 1.0.0 is depending on new undici which is not supported on Node.js 16 (Alpine), but it is working on Node.js 18 (Debian).
Pinning cheerio to `1.0.0-rc.12` could solve the issue.
The auto test actually showed the error, I don't why I ignored it, lol.
https://github.com/louislam/uptime-kuma/actions/runs/11076765407/job/30780591154

Pin cheerio to avoid the breaking change of undici

---

server/notification-providers/serverchan.js

Fixes #(issue)
UptimeKuma has a notification provider called ServerChan that released a new branch version. This PR adds compatibility for the new branch (by adjusting the API entry through the Sendkey recognition)

Add serverchan3 support for  serverchan notification provider

---

server/notification-providers/slack.js

Fixes https://github.com/louislam/uptime-kuma/pull/5196#issuecomment-2416740399
Apparently, I missed that the slack monitor chnage had not been tested
Mixing `this` and `static` is not a good idea.
Thanks @ro7it for the report

fix: slack rich notification not working correctly

---

docker/debian-base.dockerfile
extra/download-apprise.mjs

Fix Apprise download issue

---

server/database.js
server/server.js
server/utils/simple-migration-server.js

If the migration progress is too long, Docker Healthcheck could possibly restart Uptime Kuma. So we have to start a server.
Also display simple progress on the page.

Fix: Docker Healthcheck is not happy during migration

---

db/knex_migrations/2024-11-27-1927-fix-info-json-data-type.js
server/database.js

Fix #5087 and fix migration state

---

src/components/notifications/Slack.vue
src/lang/en.json

Add help text about how to use the slack `Username` and the difference from mentions.
Fixes #4560 
My slack test message:

docs: add slack username helptext

---

server/model/monitor.js

Fixes #5296 
Fixes #5277
- Add `monitor_tag.value` attribute in `getMonitorTag` SELECT
- Add `monitor_id` and `value` for each tag in `preparePreloadData`
Because those two attributes were missing, the `DELETE monitor_tag WHERE [...]` wasn't touching any line because of the empty (null/undefined) parameters.

fix(tags): Fix the tag deletion

---

server/database.js
server/embedded-mariadb.js

- Improve file permissions
- Use the database username, same as the linux user.

Fix: Embedded MariaDB startup issue

---

server/notification-providers/slack.js

only allow for valid urls in slack button

---

src/components/notifications/SendGrid.vue

Fixed: When selecting the SendGrid alert time and entering the "From Email" in the: name format, this gives a validation error
Fixes #5314 
https://github.com/user-attachments/assets/bc8478ee-eb90-4641-92f6-91fc9e28fe3b

fix #5314 Email Address Friendly Name Error

---

server/model/monitor.js
server/socket-handlers/status-page-socket-handler.js

Fixes #5336
Note: If I run ESLint, I get `41897 problems (41897 errors, 0 warnings)` by using `lint:js`, because `error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style`.

fix(status page): Make sure the group deletion is correctly handled when `groupIDList` is empty

---

src/pages/EditMonitor.vue

When editing a monitor, the timeout default value is automatically set. While the monitor is not saved, the value previously set by the user is used (even if another value is shown in the UI). But still, the correct value wans't defined. This was caused by f059d543, which were changing the timeout when monitor type were changed.
Fixes #5337 

Fix the timeout value

---

src/assets/app.scss

I noticed that, in some cases, when the list of probes is displayed downward, the save bar overlaps this menu, which can be quite inconvenient for selecting the different probes.
Fixes #(issue)
I have therefore made sure that this menu no longer overlaps the list.
Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it …

Fix the save bar of the maintenance menu

---

src/components/EditMonitorConditions.vue
test/e2e/specs/monitor-form.spec.js

The first PR related to monitors conditions were adding an empty condition. This has been removed since an empty condition disallow monitor saving. Please note this merge may be unwanted the default condition were a feature (but maybe unwished after all?). 
E2E has been updated to avoid considering we have a default condition (all `conditions` count has been reduced by 1, etc).
Fixes #5303 
- …

feat(monitor condition): Remove the empty default condition creation

---

.dockerignore

Not sure why I added this folder in .dockerignore.

Fix push examples cannot be loaded (Docker only)

---

server/notification-providers/google-chat.js

Adding fallback text to use in notifications and platforms that don't support cards, otherwise the notification just says "Uptime Kuma sent an attachment"
Resolves #5569
- Breaking change (a fix or feature that would cause existing functionality to not work as expected)
- Other
- This change requires a …

fix: add notification-fallback for better google chat popups

---

package-lock.json
package.json
server/notification-providers/nostr.js

* Update nostr-tools to 2.10.4
* Support relays that require AUTH like auth.nostr1.com
* Tested with Node 18, 20 and 22
The motiviation is to get the library updated since the protocol is evolving quickly. There's a newer method for sending direct messages with better privacy that I'd like to implement, but it's not widely supported yet, and it requires a newer library.
Additionally, some public relays require a sender to respond to an AUTH challenge before accepting a direct message event to …

chore(deps): update nostr notification provider

---

server/notification-providers/yzj.js
server/notification.js
src/components/NotificationDialog.vue
src/components/notifications/YZJ.vue
src/components/notifications/index.js
src/lang/en.json
src/lang/zh-CN.json

Support YZJ notification provider 
| Event |  After |
------------------
| `UP` | ![image](https://github.com/user-attachments/assets/90486e44-2e1a-4138-807e-bd24efd1f883) | 
| `DOWN` | ![image](https://github.com/user-attachments/assets/e23e7645-6c97-41f2-bfbf-6d0282d9bf68) | 
| Certificate-expiry | ![image](https://github.com/user-attachments/assets/ab68158c-0d1b-4ac2-a854-20ff28db9809 …

feat: Support YZJ notification provider

---

server/monitor-types/dns.js

- Node.js gets txt record in an array of array (even as arrays of only one item). https://www.tutorialspoint.com/node-js-dns-resolvetxt-method
Conditions with the "contains" operator treats the txt records as an array and do not allow to check for substring. This change flattens the array before the condition check.
- Allows for TXT records to be evaluated as strings instead of arrays for "contains" operator to evaluate properly
- Provide additional details here.
N/A
Example of a condition evaluation this tries to fix:
We have a txt value that may change but have one substring I want to …

fix: flat txt records before conditions check

---

server/notification-providers/mattermost.js

- The mattermost notification provider doesn't include the monitor name in the notifications.
- Relates to #5510
#3801 changed the mattermost notification provider to use `monitorJSON.pathName` instead of `monitorJSON.name` in the title of the notification. This introduced a bug, as the `monitorJSON.pathName` only includes items higher in the path and not the name of the monitor itself (which I'm assuming is it's intended behavior). This PR will add the name of the monitor at the end, displaying the path and the monitor name as well.
Note: This will make it / keep it inconsistent with other providers as they do not include the path, a PR (#5485) addressing this was merged before, but got rolled back manually as (I'm assuming) it omitted …

fix: Mattermost notification provider not sending service name

---

src/components/MonitorListItem.vue
src/components/Tag.vue

- It resolves an issue where tags overlap in the UI when multiple tags are assigned to a monitor or group and span several lines.
- This pull request enhances the UI by adding proper spacing between tags that appear on multiple lines, ensuring they no longer overlap.
- Relates to #5773
- Resolves #5773
- Fixes #5773
**Before:**
**After:**
Provide any relevant details to assist reviewers in understanding the changes.
</p>
**Key Considerations**:
- **Design decisions** – Added a my-1 class to improve vertical spacing between tag …

fix(dashboard): prevent y-overlapping of tags by adding a gap #5773

---

server/notification-providers/discord.js

Add default avatar in discord notifications

---

src/i18n.js

- This PR allows UK to match regional locale code from no-regional locale code. For example, if `it` is used, UK will check if `it-IT` exists as a translation, and if it does, will use it.
- Fixes #5909

Improve i18n language matching

---

server/notification-providers/google-chat.js
src/components/notifications/GoogleChat.vue
src/lang/en.json

Current Google Chat provider (cardsV2) in 2.0.0:beta.3 shows no body text at all in Android (Chat + Gmail) popups. That makes DOWN/UP Popups alerts unusable. Solution: Separate plain‑text provider without reverting the cardsv2 for Web/iOS users. I would just add a new notification provider with old plain text logic.
- #5476 
- #5569 
- #5776 
- related google issue https://issuetracker.google.com/issues/283746283
- Android popup body = empty (no status).
- cardsV2 + fallbackText effectively ignored by Android clients.
- Hybrid (text + card) causes duplicate messages on iOS.
- Upstream Google issue no fix for 2+ years 
New provider: “Google Workspace (Legacy)”
- Sends pure plain text (pre‑beta style).
- Leaves existing “Google Chat” provider untouched.
- Clearly marked as Legacy / …

feat: Templating and plaintext for Google Workspace Notification Provider

---

src/assets/app.scss

Fix monitor name cropping in nested groups (#5981)

---

src/components/HeartbeatBar.vue

Extract CSS class logic to getBeatClasses method, which resolves Vue template scope issues with imported constants.
</p>
We kindly ask you to refrain from pinging maintainers unless absolutely necessary. Pings are for critical/urgent pull requests that require immediate attention.
</p>
</details>
- HeartbeatBar component was displaying green beats for down monitors …

fix: HeartbeatBar DOWN status showing green instead of red
